/** The hash of the data contracts: the persisted query cache is discarded when it changes. Generated by pnpm gen. */
export const CACHE_BUSTER = 'd0b90efae5012fb33c97d81f38e352368d9c4710e66dda9c269a86312f8b5d3d';
