/** The hash of the data contracts: the persisted query cache is discarded when it changes. Generated by pnpm gen. */
export const CACHE_BUSTER = 'a012a8ca78a8ceb3a8239653c210219c754b38432b65305a991a54e556efe6c7';
