/** The hash of the data contracts: the persisted query cache is discarded when it changes. Generated by pnpm gen. */
export const CACHE_BUSTER = '6fd860bb9c594b4a3a612d0c01e2ceb7b2ec3ebca00d8fb3415af3abeede92d9';
