import { catalog as boxCatalog } from '#primitives/box';
import { catalog as breathingCatalog } from '#primitives/breathing';
import { catalog as curtainCatalog } from '#primitives/curtain';
import { catalog as iconCatalog } from '#primitives/icon';
import { catalog as imageCatalog } from '#primitives/image';
import { catalog as pressableCatalog } from '#primitives/pressable';
import { catalog as scrollCatalog } from '#primitives/scroll';
import { catalog as surfaceCatalog } from '#primitives/surface';
import { catalog as switchCatalog } from '#primitives/switch';
import { catalog as textCatalog } from '#primitives/text';
import { catalog as textFieldCatalog } from '#primitives/text-field';
import { catalog as themeCatalog } from '#primitives/theme';
import { catalog as buttonCatalog } from '#components/button';
import { catalog as emptyStateCatalog } from '#components/empty-state';
import { catalog as labelBarCatalog } from '#components/label-bar';
import { catalog as segmentedControlCatalog } from '#components/segmented-control';
import { catalog as skeletonCatalog } from '#components/skeleton';
import { catalog as topBarCatalog } from '#components/top-bar';
import type { CatalogItem } from '#lib/catalogue';

/** Every component catalogue entry, tagged with the level of its place. Generated by pnpm gen from the *.catalog.tsx files. */
export const REGISTRY = [
  { level: 'L0', entry: boxCatalog },
  { level: 'L0', entry: breathingCatalog },
  { level: 'L0', entry: curtainCatalog },
  { level: 'L0', entry: iconCatalog },
  { level: 'L0', entry: imageCatalog },
  { level: 'L0', entry: pressableCatalog },
  { level: 'L0', entry: scrollCatalog },
  { level: 'L0', entry: surfaceCatalog },
  { level: 'L0', entry: switchCatalog },
  { level: 'L0', entry: textCatalog },
  { level: 'L0', entry: textFieldCatalog },
  { level: 'L0', entry: themeCatalog },
  { level: 'L1', entry: buttonCatalog },
  { level: 'L1', entry: emptyStateCatalog },
  { level: 'L1', entry: labelBarCatalog },
  { level: 'L1', entry: segmentedControlCatalog },
  { level: 'L1', entry: skeletonCatalog },
  { level: 'L1', entry: topBarCatalog },
] as const satisfies readonly CatalogItem[];
