import { catalog as boxCatalog } from '#primitives/box';
import { catalog as iconCatalog } from '#primitives/icon';
import { catalog as imageCatalog } from '#primitives/image';
import { catalog as pressableCatalog } from '#primitives/pressable';
import { catalog as surfaceCatalog } from '#primitives/surface';
import { catalog as textCatalog } from '#primitives/text';
import { catalog as textFieldCatalog } from '#primitives/text-field';
import { catalog as themeCatalog } from '#primitives/theme';
import { catalog as badgeCatalog } from '#components/badge';
import { catalog as buttonCatalog } from '#components/button';
import { catalog as chipCatalog } from '#components/chip';
import { catalog as emptyStateCatalog } from '#components/empty-state';
import { catalog as paperCatalog } from '#components/paper';
import { catalog as sectionTitleCatalog } from '#components/section-title';
import { catalog as skeletonCatalog } from '#components/skeleton';
import type { CatalogItem } from '#lib/catalogue';

/** Every component catalogue entry, tagged with the level of its place. Generated by pnpm gen from the *.catalog.tsx files. */
export const REGISTRY: readonly CatalogItem[] = [
  { level: 'L0', entry: boxCatalog },
  { level: 'L0', entry: iconCatalog },
  { level: 'L0', entry: imageCatalog },
  { level: 'L0', entry: pressableCatalog },
  { level: 'L0', entry: surfaceCatalog },
  { level: 'L0', entry: textCatalog },
  { level: 'L0', entry: textFieldCatalog },
  { level: 'L0', entry: themeCatalog },
  { level: 'L1', entry: badgeCatalog },
  { level: 'L1', entry: buttonCatalog },
  { level: 'L1', entry: chipCatalog },
  { level: 'L1', entry: emptyStateCatalog },
  { level: 'L1', entry: paperCatalog },
  { level: 'L1', entry: sectionTitleCatalog },
  { level: 'L1', entry: skeletonCatalog },
];
