import type { ExpoConfig } from 'expo/config/index.js';
import { CodeGenerator, withMainActivity } from 'expo/config-plugins.js';
import type { ConfigPlugin } from 'expo/config-plugins.js';

/** How the block merged into the generated activity is named, so a later prebuild replaces it rather than doubling it. */
const FAST_FRAMES = 'humanite-fast-frames';

/** Where it goes: straight after the activity has come up, which is the first moment it has a window. */
const AFTER_CREATE = /super\.onCreate\(null\)/;

/**
 * What the activity asks the display for, in Kotlin, merged into the activity Expo generates.
 *
 * `requestedFrameRate` is a vote and not a setting: Android counts it only on the frames the view actually draws, and
 * forgets it the moment the app stops drawing. A reader holding still on an article costs nothing, and the panel comes
 * up to speed for a drag and drops back by itself. Pinning a display mode — the other way to the same rate — would
 * hold the panel there for as long as the app is open, whether or not anything moved.
 *
 * The rate is read off the display rather than written down: panels differ, a reader may have capped theirs in the
 * phone's own settings, and the fastest mode of whatever is in front of them is the only right answer. Only the modes
 * at the size already showing are considered — the others would be a change of resolution, which is not what is being
 * asked for.
 *
 * Android 15 is where the vote exists. Before it a window could only pin a mode, which is the trade this refuses, so
 * an older phone is left exactly as it was.
 */
const FAST_FRAMES_KOTLIN = `
      // @generated by ${FAST_FRAMES}: the window names the fastest rate the display in front of the reader can do.
      // The reasoning is in apps/mobile/app.config.ts.
      val showing = window.windowManager.defaultDisplay?.mode
      val fastest = (window.windowManager.defaultDisplay?.supportedModes ?: emptyArray())
        .filter { showing == null || (it.physicalWidth == showing.physicalWidth && it.physicalHeight == showing.physicalHeight) }
        .maxByOrNull { it.refreshRate }
      if (fastest != null) {
        window.attributes = window.attributes.also { it.preferredRefreshRate = fastest.refreshRate }
      }`;

/**
 * Asks the phone's display for every frame it has, on the frames this app draws.
 *
 * Measured on the A065 on 25/09/2026: the panel is a 120 Hz one, the reader's own setting is 120, and the app was
 * drawn at 90.0 Hz while the phone's launcher was drawn at 119.9 Hz in the same second, on the same gesture. The cause
 * is on the phone and is written in its own dump — `frameRateCategoryRate {normal=60.0, high=90.0}`: a window that
 * asks for nothing is sorted into a category, and this panel answers the high category with 90. Only a window naming a
 * rate is given that rate, which is what the one other app seen asking for it receives
 * (`requestedFrameRate: {120.00 Hz FrameRateCompatibility::Exact}`).
 *
 * It is a plugin and not a file of the app because `apps/mobile/android` is generated: a line written there by hand is
 * a line the next prebuild throws away. It touches the activity and nothing in JavaScript, so it holds for every
 * screen the paper will ever have, including the ones not written yet. It lives in this file rather than beside it
 * because Expo compiles this one file and requires whatever it imports as it stands — a TypeScript module next door
 * is a module the configuration cannot load.
 */
const withFastFrames: ConfigPlugin = (expo) =>
  withMainActivity(expo, (activity) => {
    if (activity.modResults.language !== 'kt') {
      throw new Error(`fast-frames : l’activité générée est en ${activity.modResults.language}, attendu kt`);
    }
    const merged = CodeGenerator.mergeContents({
      src: activity.modResults.contents,
      newSrc: FAST_FRAMES_KOTLIN,
      tag: FAST_FRAMES,
      anchor: AFTER_CREATE,
      offset: 1,
      comment: '//',
    });
    if (!merged.didMerge && !merged.didClear) {
      throw new Error('fast-frames : `super.onCreate(null)` est introuvable dans l’activité générée');
    }
    return { ...activity, modResults: { ...activity.modResults, contents: merged.contents } };
  });

/**
 * Configuration of the application, read by Expo in Node, synchronously and without the context it passes: tools such
 * as knip load it with another context.
 */
const config: ExpoConfig = {
  // The name the phone prints under the icon, and the one the paper is called: the store lists it as
  // « L'Humanité - Le Journal », published by la Société Nouvelle du Journal l'Humanité. The article is part of the
  // name and the launcher had been dropping it.
  name: 'L’Humanité',
  slug: 'humanite',
  scheme: 'humanite',
  version: '0.0.0',
  platforms: ['ios', 'android'],
  orientation: 'portrait',
  // The paper's own mark, as the journal draws it: a red square with the H of its masthead in white. It is taken from
  // the app the journal publishes (6.2.0) rather than drawn again, because it is theirs and because a second drawing
  // of a mark is a mark that drifts. The red is the palette's `uiRed` to the digit, which is where the palette got it.
  //
  // Android 12 and after paint a mark on the field they show before an app has run, and paint the launcher's when an
  // app declares none. Declaring none left Expo's placeholder there — a grid of grey circles — on the launcher and on
  // that field alike.
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  ios: { bundleIdentifier: 'dev.humanite.app' },
  android: {
    package: 'dev.humanite.app',
    // The mark again, as the two pieces Android asks for since Oreo: the foreground it masks to whatever shape the
    // launcher uses, and the ground behind it. The foreground already carries the red square, so the ground is only
    // seen where the mask cuts past its corners, and it is the same red.
    adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: '#f13c47' },
    // React Native 0.86 registers its back callback on API 36 devices only: the system back would close the app.
    predictiveBackGestureEnabled: false,
    // Android's automatic backup copies the app's own directory to the reader's Drive and restores it onto whatever
    // phone they next sign into. The store in that directory holds what the paper answered; the keystore holding the
    // subscriber's token does not travel, and is asked not to (ADR-0034). Letting the backup run would carry the one
    // half to a device the other half was refused, and carry it through a service neither the journal nor the reader
    // is party to.
    //
    // It costs something, and the cost is the kept articles. Measured on a capture of the journal's own app on
    // 24/09/2026: opening its favourites made no call to the service at all, and nothing the service answers carries
    // a list — `/skin` styles the toggle, `/json_parameters` says the feature exists, and that is the whole of it.
    // Both apps keep that list on the phone and nowhere else, so a reader changing phone starts their shelf again.
    // Paying it here is the narrow reading: one file holds both the shelf and the bodies a subscription paid for, and
    // until those are two files there is no way to send one without the other.
    allowBackup: false,
  },
  plugins: [
    'expo-router',
    // The field the phone paints before a line of this app has run, and the one it paints behind the app after.
    //
    // The ground is the paper's — white, or the measured #141414 under a dark system — and the mark on it is the
    // paper's own, which Android masks to a circle at the middle of the field. The masthead is not put here: it is
    // set in a face the app loads, a picture of it would be a second drawing of the same words, and Android's mask
    // would cut a wordmark in half. The app lays it on the same ground as soon as the faces are in, so nothing
    // flashes between the phone's field and the app's.
    //
    // The image is declared and not left out. Left out, the plugin writes no drawable and still points the theme at
    // one: `styles.xml` named `@drawable/splashscreen_logo` in a tree that had no such file, which is a build that
    // cannot link. Given no plugin at all, Expo puts its own placeholder there instead.
    //
    // The values are the palette's `white` and `darkBackground`, written out because a config is read by Node,
    // before anything of the app is built, and cannot import a token.
    [
      'expo-splash-screen',
      { image: './assets/splash-icon.png', backgroundColor: '#ffffff', dark: { backgroundColor: '#141414' } },
    ],
  ],
  experiments: { typedRoutes: true, reactCompiler: true },
  updates: { enabled: false },
};

/**
 * The configuration, with the one thing a plugin has to do to it. It is applied to the object rather than named in
 * `plugins`, which takes the name of a package: this one is written here.
 */
export default withFastFrames(config);
