import type { ExpoConfig } from 'expo/config/index.js';
import { CodeGenerator, IOSConfig, withAppDelegate, withInfoPlist, withMainActivity } from 'expo/config-plugins.js';
import type { ConfigPlugin } from 'expo/config-plugins.js';

/**
 * The version of the app, and of the release that ships it: a tag `vX.Y.Z` publishes `X.Y.Z`, and the release workflow
 * refuses a tag this line does not name (`.github/workflows/release.yml`).
 */
const VERSION = '0.1.5';

/**
 * The integer Android orders two builds of one app by, and refuses to install a lower one over: each part of the
 * version on two digits, so 0.1.0 is 100 and 1.2.3 is 10203. Written by hand, it would be one more line to forget at
 * every release, and a phone that got 0.2.0 at the same number as 0.1.0 could not tell the two apart.
 */
const versionCode = (version: string): number =>
  version.split('.').reduce((code, part) => code * 100 + Number.parseInt(part, 10), 0);

/**
 * Who a build says it is: its package and bundle identifier, the name under its icon, and the scheme its links open.
 *
 * The plain identity belongs to the release key. Android refuses to install an app over one of the same identifier
 * signed by another key, so a build of the debug key under that identifier — a dev client, a local build, a build of
 * the CI — would stand, on a phone, between the reader and every release. Only the release workflow asks for it; every
 * other build is the `.dev` one, beside the release rather than in its place, and its links open in it and not in the
 * release (ADR-0039).
 */
const IDENTITIES = {
  release: { id: 'alexandrevl.humanite.app', name: 'L’Humanité', scheme: 'humanite' },
  development: { id: 'alexandrevl.humanite.app.dev', name: 'L’Humanité dev', scheme: 'humanite-dev' },
} as const;

/** The identity `APP_VARIANT` asks for: `release`, or none for the development one; any other value is a mistake. */
function identityOf(variant: string | undefined): (typeof IDENTITIES)[keyof typeof IDENTITIES] {
  switch (variant) {
    case 'release':
      return IDENTITIES.release;
    case undefined:
    case '':
    case 'development':
      return IDENTITIES.development;
    default:
      throw new Error(`APP_VARIANT=${variant} : release, development ou rien attendu`);
  }
}

const IDENTITY = identityOf(process.env['APP_VARIANT']);

/** How the block merged into the generated activity is named, so a later prebuild replaces it rather than doubling it. */
const FAST_FRAMES = 'humanite-fast-frames';

/** Where it goes: straight after the activity has come up, which is the first moment it has a window. */
const AFTER_CREATE = /super\.onCreate\(null\)/;

/**
 * What the activity asks the display for, in Kotlin, merged into the activity Expo generates.
 *
 * `requestedFrameRate` is a vote and not a setting: Android counts it only on the frames the view actually draws, and
 * forgets it the moment the app stops drawing. A reader holding still on an article costs nothing, and the panel comes
 * up to speed for a drag and drops back by itself. Pinning a display mode — the other way to the same rate — would
 * hold the panel there for as long as the app is open, whether or not anything moved.
 *
 * The rate is read off the display rather than written down: panels differ, a reader may have capped theirs in the
 * phone's own settings, and the fastest mode of whatever is in front of them is the only right answer. Only the modes
 * at the size already showing are considered — the others would be a change of resolution, which is not what is being
 * asked for.
 *
 * Android 15 is where the vote exists. Before it a window could only pin a mode, which is the trade this refuses, so
 * an older phone is left exactly as it was.
 */
const FAST_FRAMES_KOTLIN = `
      // @generated by ${FAST_FRAMES}: the window names the fastest rate the display in front of the reader can do.
      // The reasoning is in apps/mobile/app.config.ts.
      val showing = window.windowManager.defaultDisplay?.mode
      val fastest = (window.windowManager.defaultDisplay?.supportedModes ?: emptyArray())
        .filter { showing == null || (it.physicalWidth == showing.physicalWidth && it.physicalHeight == showing.physicalHeight) }
        .maxByOrNull { it.refreshRate }
      if (fastest != null) {
        window.attributes = window.attributes.also { it.preferredRefreshRate = fastest.refreshRate }
      }`;

/**
 * Asks the phone's display for every frame it has, on the frames this app draws.
 *
 * Measured on the A065 on 25/09/2026: the panel is a 120 Hz one, the reader's own setting is 120, and the app was
 * drawn at 90.0 Hz while the phone's launcher was drawn at 119.9 Hz in the same second, on the same gesture. The cause
 * is on the phone and is written in its own dump — `frameRateCategoryRate {normal=60.0, high=90.0}`: a window that
 * asks for nothing is sorted into a category, and this panel answers the high category with 90. Only a window naming a
 * rate is given that rate, which is what the one other app seen asking for it receives
 * (`requestedFrameRate: {120.00 Hz FrameRateCompatibility::Exact}`).
 *
 * It is a plugin and not a file of the app because `apps/mobile/android` is generated: a line written there by hand is
 * a line the next prebuild throws away. It touches the activity and nothing in JavaScript, so it holds for every
 * screen the paper will ever have, including the ones not written yet. It lives in this file rather than beside it
 * because Expo compiles this one file and requires whatever it imports as it stands — a TypeScript module next door
 * is a module the configuration cannot load.
 */
const withFastFrames: ConfigPlugin = (expo) =>
  withMainActivity(expo, (activity) => {
    if (activity.modResults.language !== 'kt') {
      throw new Error(`fast-frames : l’activité générée est en ${activity.modResults.language}, attendu kt`);
    }
    const merged = CodeGenerator.mergeContents({
      src: activity.modResults.contents,
      newSrc: FAST_FRAMES_KOTLIN,
      tag: FAST_FRAMES,
      anchor: AFTER_CREATE,
      offset: 1,
      comment: '//',
    });
    if (!merged.didMerge && !merged.didClear) {
      throw new Error('fast-frames : `super.onCreate(null)` est introuvable dans l’activité générée');
    }
    return { ...activity, modResults: { ...activity.modResults, contents: merged.contents } };
  });

/** How the lines the scenes plugin writes into generated files are marked, so a later prebuild knows them for its own. */
const SCENES = 'humanite-scenes';

/** The one scene the app runs in and the class that opens its window, key for key as SDK 58's template declares them. */
const SCENE_MANIFEST = {
  UIApplicationSupportsMultipleScenes: false,
  UISceneConfigurations: {
    UIWindowSceneSessionRoleApplication: [
      {
        UISceneConfigurationName: 'Default Configuration',
        UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
      },
    ],
  },
};

/** The scene's delegate. Expo's base class does all of it: it opens the window and hands every event on. */
const SCENE_DELEGATE_SWIFT = `// @generated by ${SCENES}: the reasoning is in apps/mobile/app.config.ts.
internal import Expo

@objc(SceneDelegate)
class SceneDelegate: ExpoAppSceneDelegate {}
`;

/** How the template's app delegate declares itself, and how it declares itself once the scene can reach its factory. */
const OWN_DELEGATE = 'class AppDelegate: ExpoAppDelegate {';
const PROVIDING_DELEGATE = 'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {';

/** The window the template's app delegate opens for itself, with React Native started in it. */
const OWN_WINDOW =
  /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\([^)]*\)\n#endif\n/;

/** What stands where that window was. */
const WINDOW_LEFT = `    // @generated by ${SCENES}: the window is the scene's, and SceneDelegate starts React Native in it.\n`;

/** The template's app delegate, handing its factory to the scene and opening no window of its own. */
const leaveWindowToScene = (contents: string): string => {
  const providing = contents.includes(PROVIDING_DELEGATE)
    ? contents
    : contents.replace(OWN_DELEGATE, PROVIDING_DELEGATE);
  if (!providing.includes(PROVIDING_DELEGATE)) {
    throw new Error(`scenes : \`${OWN_DELEGATE}\` est introuvable dans le délégué généré`);
  }
  if (providing.includes(WINDOW_LEFT)) {
    return providing;
  }
  if (!OWN_WINDOW.test(providing)) {
    throw new Error('scenes : la fenêtre que le délégué généré ouvre lui-même est introuvable');
  }
  return providing.replace(OWN_WINDOW, WINDOW_LEFT);
};

/**
 * Lets iOS open the app into a scene, which is the only way the iOS 27 SDK will open it at all.
 *
 * Built with Xcode 27 and started on iOS 27 on 25/09/2026, the app never drew a frame: UIKit stopped it as the scene
 * was being created, in `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`. iOS 26 only warned an app
 * whose delegate still opens its own window; the SDK after it refuses to start one. Expo 57.0.25 ships the delegate a
 * scene needs (`ExpoAppSceneDelegate`) but SDK 57's native template never names it — SDK 58's does — so this writes
 * the three things SDK 58's template carries: the manifest naming a scene delegate, that delegate, and an app delegate
 * that leaves the window to it.
 *
 * The app delegate keeps its own link handlers. The scene hands each link to them, then to React Native only if they
 * have not already done so (`SceneEventForwarder` in Expo), so a link is still announced once.
 *
 * It is a plugin and not a file of the app for the reason the one above is: `apps/mobile/ios` is generated. It goes
 * when the app moves to SDK 58, whose template does all three.
 */
const withScenes: ConfigPlugin = (expo) => {
  const manifested = withInfoPlist(expo, (plist) => ({
    ...plist,
    modResults: { ...plist.modResults, UIApplicationSceneManifest: SCENE_MANIFEST },
  }));
  const delegated = IOSConfig.XcodeProjectFile.withBuildSourceFile(manifested, {
    filePath: 'SceneDelegate.swift',
    contents: SCENE_DELEGATE_SWIFT,
    overwrite: true,
  });
  return withAppDelegate(delegated, (delegate) => {
    if (delegate.modResults.language !== 'swift') {
      throw new Error(`scenes : le délégué généré est en ${delegate.modResults.language}, attendu swift`);
    }
    return {
      ...delegate,
      modResults: { ...delegate.modResults, contents: leaveWindowToScene(delegate.modResults.contents) },
    };
  });
};

/**
 * Configuration of the application, read by Expo in Node, synchronously and without the context it passes: tools such
 * as knip load it with another context.
 */
const config: ExpoConfig = {
  // The name the phone prints under the icon, and the one the paper is called: the store lists it as
  // « L'Humanité - Le Journal », published by la Société Nouvelle du Journal l'Humanité. The article is part of the
  // name and the launcher had been dropping it. A development build adds that it is one.
  name: IDENTITY.name,
  slug: 'humanite',
  scheme: IDENTITY.scheme,
  version: VERSION,
  platforms: ['ios', 'android'],
  orientation: 'portrait',
  // The paper's own mark, as the journal draws it: a red square with the H of its masthead in white. It is taken from
  // the app the journal publishes (6.2.0) rather than drawn again, because it is theirs and because a second drawing
  // of a mark is a mark that drifts. The red is the palette's `uiRed` to the digit, which is where the palette got it.
  //
  // Android 12 and after paint a mark on the field they show before an app has run, and paint the launcher's when an
  // app declares none. Declaring none left Expo's placeholder there — a grid of grey circles — on the launcher and on
  // that field alike.
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  ios: { bundleIdentifier: IDENTITY.id },
  android: {
    package: IDENTITY.id,
    versionCode: versionCode(VERSION),
    // The mark again, as the two pieces Android asks for since Oreo: the foreground it masks to whatever shape the
    // launcher uses, and the ground behind it. The foreground already carries the red square, so the ground is only
    // seen where the mask cuts past its corners, and it is the same red.
    adaptiveIcon: { foregroundImage: './assets/adaptive-icon.png', backgroundColor: '#f13c47' },
    // React Native 0.86 registers its back callback on API 36 devices only: the system back would close the app.
    predictiveBackGestureEnabled: false,
    // Android's automatic backup copies the app's own directory to the reader's Drive and restores it onto whatever
    // phone they next sign into. The store in that directory holds what the paper answered; the keystore holding the
    // subscriber's token does not travel, and is asked not to (ADR-0034). Letting the backup run would carry the one
    // half to a device the other half was refused, and carry it through a service neither the journal nor the reader
    // is party to.
    //
    // It costs something, and the cost is the kept articles. Measured on a capture of the journal's own app on
    // 24/09/2026: opening its favourites made no call to the service at all, and nothing the service answers carries
    // a list — `/skin` styles the toggle, `/json_parameters` says the feature exists, and that is the whole of it.
    // Both apps keep that list on the phone and nowhere else, so a reader changing phone starts their shelf again.
    // Paying it here is the narrow reading: one file holds both the shelf and the bodies a subscription paid for, and
    // until those are two files there is no way to send one without the other.
    allowBackup: false,
  },
  plugins: [
    'expo-router',
    // The field the phone paints before a line of this app has run, and the one it paints behind the app after.
    //
    // The ground is the paper's — white, or the measured #141414 under a dark system — and the mark on it is the
    // paper's own, which Android masks to a circle at the middle of the field. The masthead is not put here: it is
    // set in a face the app loads, a picture of it would be a second drawing of the same words, and Android's mask
    // would cut a wordmark in half. The app lays it on the same ground as soon as the faces are in, so nothing
    // flashes between the phone's field and the app's.
    //
    // The image is declared and not left out. Left out, the plugin writes no drawable and still points the theme at
    // one: `styles.xml` named `@drawable/splashscreen_logo` in a tree that had no such file, which is a build that
    // cannot link. Given no plugin at all, Expo puts its own placeholder there instead.
    //
    // The values are the palette's `white` and `darkBackground`, written out because a config is read by Node,
    // before anything of the app is built, and cannot import a token.
    [
      'expo-splash-screen',
      { image: './assets/splash-icon.png', backgroundColor: '#ffffff', dark: { backgroundColor: '#141414' } },
    ],
  ],
  experiments: { typedRoutes: true, reactCompiler: true },
  updates: { enabled: false },
};

/**
 * The configuration, with the two things plugins have to do to it. They are applied to the object rather than named in
 * `plugins`, which takes the name of a package: these are written here.
 */
export default withScenes(withFastFrames(config));
