import { deepFreeze } from '@huma/kit/records';
import type { FormatSpec } from './types.ts';

/**
 * Format 1: MADR 4.0.0 translated into French, every section required, rules stated with the BCP 14 keywords. Once an
 * ADR is decided in this format, a change of these values or of their reading that refuses it is a new format.
 */
export const FORMAT_1 = deepFreeze({
  version: 1,
  sections: [
    { key: 'context', title: 'Contexte et problème' },
    { key: 'criteria', title: 'Critères de décision' },
    { key: 'options', title: 'Options étudiées' },
    { key: 'decision', title: 'Décision' },
    { key: 'prosAndCons', title: 'Avantages et inconvénients des options' },
    { key: 'moreInformation', title: 'Informations complémentaires' },
  ],
  consequences: 'Conséquences',
  keywords: {
    must: { label: 'DOIT', forms: ['DOIT', 'DOIVENT'], binding: true },
    mustNot: { label: 'NE DOIT PAS', forms: ['NE DOIT PAS', 'NE DOIVENT PAS'], binding: true },
    may: { label: 'PEUT', forms: ['PEUT', 'PEUVENT'], binding: false },
  },
  negation: { before: ['NE', 'N’', "N'"], after: ['PAS', 'JAMAIS', 'PLUS', 'POINT', 'RIEN'] },
  forbiddenWords: [
    'NE DEVRAIENT PAS',
    'NE DEVRAIT PAS',
    'NE DEVRONT PAS',
    'NE DEVRA PAS',
    'NE PEUVENT PAS',
    'NE PEUT PAS',
    'NON RECOMMANDEES',
    'NON RECOMMANDES',
    'NON RECOMMANDEE',
    'NON RECOMMANDE',
    'IL FAUT',
    'FAUT',
    'DEVRAIENT',
    'DEVRAIT',
    'DEVRONT',
    'DEVRA',
    'DEVONS',
    'DEVEZ',
    'DEVAIENT',
    'DEVAIT',
    'EXIGEES',
    'EXIGES',
    'EXIGEE',
    'EXIGE',
    'OBLIGATOIREMENT',
    'OBLIGATOIRES',
    'OBLIGATOIRE',
    'RECOMMANDEES',
    'RECOMMANDES',
    'RECOMMANDEE',
    'RECOMMANDE',
    'REQUISES',
    'REQUISE',
    'REQUIS',
    'FACULTATIVES',
    'FACULTATIFS',
    'FACULTATIVE',
    'FACULTATIF',
    'OPTIONNELLES',
    'OPTIONNELS',
    'OPTIONNELLE',
    'OPTIONNEL',
    'INTERDITES',
    'INTERDITS',
    'INTERDITE',
    'INTERDIT',
    'MUST NOT',
    'SHOULD NOT',
    'SHALL NOT',
    'MUST',
    'SHOULD',
    'SHALL',
    'MAY',
    'REQUIRED',
    'RECOMMENDED',
    'OPTIONAL',
  ],
  valences: { good: 'Bien', neutral: 'Neutre', bad: 'Mauvais' },
  labels: {
    because: 'parce que',
    becauseElided: 'parce qu’',
    chosenOption: 'Option retenue',
    reevaluation: 'Réévaluation',
    criterionPrefix: 'C',
    rulePrefix: 'R',
  },
  punctuation: {
    labelSeparator: ' — ',
    colon: ' : ',
    comma: ', ',
    quoteOpen: '« ',
    quoteClose: ' »',
    citationOpen: '(',
    citationClose: ')',
    questionMark: '?',
  },
  title: { maxCodePoints: 60, forbiddenCharacters: [':'], finalPunctuation: ['.', '!', '?', ';', ',', '…'] },
  limits: { words: 900, minOptions: 2, maxSupersedes: 8, headingDepth: 3 },
  markdown: {
    nodes: [
      'root',
      'yaml',
      'heading',
      'paragraph',
      'list',
      'listItem',
      'table',
      'tableRow',
      'tableCell',
      'code',
      'text',
      'emphasis',
      'strong',
      'inlineCode',
      'link',
    ],
    fences: ['```', '~~~'],
  },
  links: { schemes: ['https:'] },
} as const satisfies FormatSpec);
