import type { FormatSpec } from './types.ts';

/**
 * Format 1: MADR 4.0.0 translated into French, every section required, rules stated with the BCP 14 keywords.
 * Published: an ADR decided in this format is checked against these values forever, so they never change.
 */
export const FORMAT_1 = {
  version: 1,
  sections: [
    { key: 'context', title: 'Contexte et problème' },
    { key: 'criteria', title: 'Critères de décision' },
    { key: 'options', title: 'Options étudiées' },
    { key: 'decision', title: 'Décision' },
    { key: 'prosAndCons', title: 'Avantages et inconvénients des options' },
    { key: 'moreInformation', title: 'Informations complémentaires' },
  ],
  consequences: 'Conséquences',
  keywords: {
    must: { label: 'DOIT', forms: ['DOIT', 'DOIVENT'], binding: true },
    mustNot: { label: 'NE DOIT PAS', forms: ['NE DOIT PAS', 'NE DOIVENT PAS'], binding: true },
    may: { label: 'PEUT', forms: ['PEUT', 'PEUVENT'], binding: false },
  },
  forbiddenWords: [
    'NE DEVRAIENT PAS',
    'NE DEVRAIT PAS',
    'NE DEVRONT PAS',
    'NE DEVRA PAS',
    'NE PEUVENT PAS',
    'NE PEUT PAS',
    'NON RECOMMANDEES',
    'NON RECOMMANDES',
    'NON RECOMMANDEE',
    'NON RECOMMANDE',
    'IL FAUT',
    'FAUT',
    'DEVRAIENT',
    'DEVRAIT',
    'DEVRONT',
    'DEVRA',
    'DEVONS',
    'DEVEZ',
    'DEVAIENT',
    'DEVAIT',
    'EXIGEES',
    'EXIGES',
    'EXIGEE',
    'EXIGE',
    'OBLIGATOIREMENT',
    'OBLIGATOIRES',
    'OBLIGATOIRE',
    'RECOMMANDEES',
    'RECOMMANDES',
    'RECOMMANDEE',
    'RECOMMANDE',
    'REQUISES',
    'REQUISE',
    'REQUIS',
    'FACULTATIVES',
    'FACULTATIFS',
    'FACULTATIVE',
    'FACULTATIF',
    'OPTIONNELLES',
    'OPTIONNELS',
    'OPTIONNELLE',
    'OPTIONNEL',
    'INTERDITES',
    'INTERDITS',
    'INTERDITE',
    'INTERDIT',
    'MUST NOT',
    'SHOULD NOT',
    'SHALL NOT',
    'MUST',
    'SHOULD',
    'SHALL',
    'MAY',
    'REQUIRED',
    'RECOMMENDED',
    'OPTIONAL',
  ],
  valences: { good: 'Bien', neutral: 'Neutre', bad: 'Mauvais' },
  labels: {
    because: 'parce que',
    becauseElided: 'parce qu’',
    chosenOption: 'Option retenue',
    reevaluation: 'Réévaluation',
    separator: ' — ',
    criterionPrefix: 'C',
    rulePrefix: 'R',
  },
  title: { maxCodePoints: 60, forbiddenCharacters: [':'], finalPunctuation: ['.', '!', '?', ';', ',', '…'] },
  limits: { words: 900, minOptions: 2, maxSupersedes: 8, headingDepth: 3 },
  markdown: {
    nodes: [
      'root',
      'yaml',
      'heading',
      'paragraph',
      'list',
      'listItem',
      'table',
      'tableRow',
      'tableCell',
      'code',
      'text',
      'emphasis',
      'strong',
      'inlineCode',
      'link',
    ],
    fences: ['```', '~~~'],
  },
} as const satisfies FormatSpec;
