// @generated by `pnpm corpus:generate` — do not edit by hand.

import i0 from './generated/images/cul-a1-hero-480.webp';
import i1 from './generated/images/cul-a1-hero-1080.webp';
import i2 from './generated/images/cul-a2-hero-480.webp';
import i3 from './generated/images/cul-a2-hero-1080.webp';
import i4 from './generated/images/cul-a2-galerie-480.webp';
import i5 from './generated/images/cul-a2-galerie-1080.webp';
import i6 from './generated/images/cul-a4-hero-480.webp';
import i7 from './generated/images/cul-a4-hero-1080.webp';
import i8 from './generated/images/cul-a5-hero-480.webp';
import i9 from './generated/images/cul-a5-hero-1080.webp';
import i10 from './generated/images/cul-a5-archives-480.webp';
import i11 from './generated/images/cul-a5-archives-1080.webp';
import i12 from './generated/images/cul-a6-hero-480.webp';
import i13 from './generated/images/cul-a6-hero-1080.webp';
import i14 from './generated/images/eco-a1-hero-480.webp';
import i15 from './generated/images/eco-a1-hero-1080.webp';
import i16 from './generated/images/eco-a1-rassemblement-480.webp';
import i17 from './generated/images/eco-a1-rassemblement-1080.webp';
import i18 from './generated/images/eco-a2-hero-480.webp';
import i19 from './generated/images/eco-a2-hero-1080.webp';
import i20 from './generated/images/eco-a3-hero-480.webp';
import i21 from './generated/images/eco-a3-hero-1080.webp';
import i22 from './generated/images/eco-a3-formation-480.webp';
import i23 from './generated/images/eco-a3-formation-1080.webp';
import i24 from './generated/images/eco-a5-hero-480.webp';
import i25 from './generated/images/eco-a5-hero-1080.webp';
import i26 from './generated/images/eco-a5-atelier-480.webp';
import i27 from './generated/images/eco-a5-atelier-1080.webp';
import i28 from './generated/images/eco-a6-hero-480.webp';
import i29 from './generated/images/eco-a6-hero-1080.webp';
import i30 from './generated/images/env-a1-hero-480.webp';
import i31 from './generated/images/env-a1-hero-1080.webp';
import i32 from './generated/images/env-a1-retenue-480.webp';
import i33 from './generated/images/env-a1-retenue-1080.webp';
import i34 from './generated/images/env-a2-hero-480.webp';
import i35 from './generated/images/env-a2-hero-1080.webp';
import i36 from './generated/images/env-a3-hero-480.webp';
import i37 from './generated/images/env-a3-hero-1080.webp';
import i38 from './generated/images/env-a3-observatoire-480.webp';
import i39 from './generated/images/env-a3-observatoire-1080.webp';
import i40 from './generated/images/env-a4-hero-480.webp';
import i41 from './generated/images/env-a4-hero-1080.webp';
import i42 from './generated/images/env-a4-cour-480.webp';
import i43 from './generated/images/env-a4-cour-1080.webp';
import i44 from './generated/images/env-a5-hero-480.webp';
import i45 from './generated/images/env-a5-hero-1080.webp';
import i46 from './generated/images/env-a6-hero-480.webp';
import i47 from './generated/images/env-a6-hero-1080.webp';
import i48 from './generated/images/fem-a1-hero-480.webp';
import i49 from './generated/images/fem-a1-hero-1080.webp';
import i50 from './generated/images/fem-a1-tournee-480.webp';
import i51 from './generated/images/fem-a1-tournee-1080.webp';
import i52 from './generated/images/fem-a2-hero-480.webp';
import i53 from './generated/images/fem-a2-hero-1080.webp';
import i54 from './generated/images/fem-a3-hero-480.webp';
import i55 from './generated/images/fem-a3-hero-1080.webp';
import i56 from './generated/images/fem-a4-hero-480.webp';
import i57 from './generated/images/fem-a4-hero-1080.webp';
import i58 from './generated/images/fem-a5-hero-480.webp';
import i59 from './generated/images/fem-a5-hero-1080.webp';
import i60 from './generated/images/fem-a6-hero-480.webp';
import i61 from './generated/images/fem-a6-hero-1080.webp';
import i62 from './generated/images/mon-a1-hero-480.webp';
import i63 from './generated/images/mon-a1-hero-1080.webp';
import i64 from './generated/images/mon-a1-negociations-480.webp';
import i65 from './generated/images/mon-a1-negociations-1080.webp';
import i66 from './generated/images/mon-a2-hero-480.webp';
import i67 from './generated/images/mon-a2-hero-1080.webp';
import i68 from './generated/images/mon-a3-hero-480.webp';
import i69 from './generated/images/mon-a3-hero-1080.webp';
import i70 from './generated/images/mon-a3-dockers-480.webp';
import i71 from './generated/images/mon-a3-dockers-1080.webp';
import i72 from './generated/images/mon-a4-hero-480.webp';
import i73 from './generated/images/mon-a4-hero-1080.webp';
import i74 from './generated/images/mon-a6-hero-480.webp';
import i75 from './generated/images/mon-a6-hero-1080.webp';
import i76 from './generated/images/pol-a1-hero-480.webp';
import i77 from './generated/images/pol-a1-hero-1080.webp';
import i78 from './generated/images/pol-a1-car-scolaire-480.webp';
import i79 from './generated/images/pol-a1-car-scolaire-1080.webp';
import i80 from './generated/images/pol-a2-hero-480.webp';
import i81 from './generated/images/pol-a2-hero-1080.webp';
import i82 from './generated/images/pol-a3-hero-480.webp';
import i83 from './generated/images/pol-a3-hero-1080.webp';
import i84 from './generated/images/pol-a3-carte-fusion-480.webp';
import i85 from './generated/images/pol-a3-carte-fusion-1080.webp';
import i86 from './generated/images/pol-a4-hero-480.webp';
import i87 from './generated/images/pol-a4-hero-1080.webp';
import i88 from './generated/images/pol-a5-hero-480.webp';
import i89 from './generated/images/pol-a5-hero-1080.webp';
import i90 from './generated/images/pol-a6-hero-480.webp';
import i91 from './generated/images/pol-a6-hero-1080.webp';
import i92 from './generated/images/soc-a1-hero-480.webp';
import i93 from './generated/images/soc-a1-hero-1080.webp';
import i94 from './generated/images/soc-a1-gymnase-480.webp';
import i95 from './generated/images/soc-a1-gymnase-1080.webp';
import i96 from './generated/images/soc-a2-hero-480.webp';
import i97 from './generated/images/soc-a2-hero-1080.webp';
import i98 from './generated/images/soc-a3-hero-480.webp';
import i99 from './generated/images/soc-a3-hero-1080.webp';
import i100 from './generated/images/soc-a3-attente-480.webp';
import i101 from './generated/images/soc-a3-attente-1080.webp';
import i102 from './generated/images/soc-a4-hero-480.webp';
import i103 from './generated/images/soc-a4-hero-1080.webp';
import i104 from './generated/images/soc-a4-atelier-480.webp';
import i105 from './generated/images/soc-a4-atelier-1080.webp';
import i106 from './generated/images/soc-a5-hero-480.webp';
import i107 from './generated/images/soc-a5-hero-1080.webp';
import i108 from './generated/images/soc-a6-hero-480.webp';
import i109 from './generated/images/soc-a6-hero-1080.webp';
import i110 from './generated/images/spo-a1-hero-480.webp';
import i111 from './generated/images/spo-a1-hero-1080.webp';
import i112 from './generated/images/spo-a1-tribunes-480.webp';
import i113 from './generated/images/spo-a1-tribunes-1080.webp';
import i114 from './generated/images/spo-a2-hero-480.webp';
import i115 from './generated/images/spo-a2-hero-1080.webp';
import i116 from './generated/images/spo-a2-tribunes-480.webp';
import i117 from './generated/images/spo-a2-tribunes-1080.webp';
import i118 from './generated/images/spo-a3-hero-480.webp';
import i119 from './generated/images/spo-a3-hero-1080.webp';
import i120 from './generated/images/spo-a4-hero-480.webp';
import i121 from './generated/images/spo-a4-hero-1080.webp';
import i122 from './generated/images/spo-a5-hero-480.webp';
import i123 from './generated/images/spo-a5-hero-1080.webp';
import i124 from './generated/images/spo-a6-hero-480.webp';
import i125 from './generated/images/spo-a6-hero-1080.webp';

/** The widths every picture is written at, narrowest first. */
export const ASSET_WIDTHS = [480, 1080] as const;

/** One of the widths a picture is written at. */
export type AssetWidth = (typeof ASSET_WIDTHS)[number];

/** Every picture of the corpus, by key: the module the bundler resolves at each width. */
export const ASSETS: Readonly<Record<string, Readonly<Record<AssetWidth, number>>>> = {
  'cul-a1-hero': { 480: i0, 1080: i1 },
  'cul-a2-hero': { 480: i2, 1080: i3 },
  'cul-a2-galerie': { 480: i4, 1080: i5 },
  'cul-a4-hero': { 480: i6, 1080: i7 },
  'cul-a5-hero': { 480: i8, 1080: i9 },
  'cul-a5-archives': { 480: i10, 1080: i11 },
  'cul-a6-hero': { 480: i12, 1080: i13 },
  'eco-a1-hero': { 480: i14, 1080: i15 },
  'eco-a1-rassemblement': { 480: i16, 1080: i17 },
  'eco-a2-hero': { 480: i18, 1080: i19 },
  'eco-a3-hero': { 480: i20, 1080: i21 },
  'eco-a3-formation': { 480: i22, 1080: i23 },
  'eco-a5-hero': { 480: i24, 1080: i25 },
  'eco-a5-atelier': { 480: i26, 1080: i27 },
  'eco-a6-hero': { 480: i28, 1080: i29 },
  'env-a1-hero': { 480: i30, 1080: i31 },
  'env-a1-retenue': { 480: i32, 1080: i33 },
  'env-a2-hero': { 480: i34, 1080: i35 },
  'env-a3-hero': { 480: i36, 1080: i37 },
  'env-a3-observatoire': { 480: i38, 1080: i39 },
  'env-a4-hero': { 480: i40, 1080: i41 },
  'env-a4-cour': { 480: i42, 1080: i43 },
  'env-a5-hero': { 480: i44, 1080: i45 },
  'env-a6-hero': { 480: i46, 1080: i47 },
  'fem-a1-hero': { 480: i48, 1080: i49 },
  'fem-a1-tournee': { 480: i50, 1080: i51 },
  'fem-a2-hero': { 480: i52, 1080: i53 },
  'fem-a3-hero': { 480: i54, 1080: i55 },
  'fem-a4-hero': { 480: i56, 1080: i57 },
  'fem-a5-hero': { 480: i58, 1080: i59 },
  'fem-a6-hero': { 480: i60, 1080: i61 },
  'mon-a1-hero': { 480: i62, 1080: i63 },
  'mon-a1-negociations': { 480: i64, 1080: i65 },
  'mon-a2-hero': { 480: i66, 1080: i67 },
  'mon-a3-hero': { 480: i68, 1080: i69 },
  'mon-a3-dockers': { 480: i70, 1080: i71 },
  'mon-a4-hero': { 480: i72, 1080: i73 },
  'mon-a6-hero': { 480: i74, 1080: i75 },
  'pol-a1-hero': { 480: i76, 1080: i77 },
  'pol-a1-car-scolaire': { 480: i78, 1080: i79 },
  'pol-a2-hero': { 480: i80, 1080: i81 },
  'pol-a3-hero': { 480: i82, 1080: i83 },
  'pol-a3-carte-fusion': { 480: i84, 1080: i85 },
  'pol-a4-hero': { 480: i86, 1080: i87 },
  'pol-a5-hero': { 480: i88, 1080: i89 },
  'pol-a6-hero': { 480: i90, 1080: i91 },
  'soc-a1-hero': { 480: i92, 1080: i93 },
  'soc-a1-gymnase': { 480: i94, 1080: i95 },
  'soc-a2-hero': { 480: i96, 1080: i97 },
  'soc-a3-hero': { 480: i98, 1080: i99 },
  'soc-a3-attente': { 480: i100, 1080: i101 },
  'soc-a4-hero': { 480: i102, 1080: i103 },
  'soc-a4-atelier': { 480: i104, 1080: i105 },
  'soc-a5-hero': { 480: i106, 1080: i107 },
  'soc-a6-hero': { 480: i108, 1080: i109 },
  'spo-a1-hero': { 480: i110, 1080: i111 },
  'spo-a1-tribunes': { 480: i112, 1080: i113 },
  'spo-a2-hero': { 480: i114, 1080: i115 },
  'spo-a2-tribunes': { 480: i116, 1080: i117 },
  'spo-a3-hero': { 480: i118, 1080: i119 },
  'spo-a4-hero': { 480: i120, 1080: i121 },
  'spo-a5-hero': { 480: i122, 1080: i123 },
  'spo-a6-hero': { 480: i124, 1080: i125 },
};
