// @generated by `pnpm --filter @huma/mock-content generate` — do not edit by hand.

import i0 from './generated/images/cul-a1-hero-320.webp';
import i1 from './generated/images/cul-a1-hero-640.webp';
import i2 from './generated/images/cul-a1-hero-1080.webp';
import i3 from './generated/images/cul-a1-hero-1600.webp';
import i4 from './generated/images/cul-a2-hero-320.webp';
import i5 from './generated/images/cul-a2-hero-640.webp';
import i6 from './generated/images/cul-a2-hero-1080.webp';
import i7 from './generated/images/cul-a2-hero-1600.webp';
import i8 from './generated/images/cul-a2-galerie-320.webp';
import i9 from './generated/images/cul-a2-galerie-640.webp';
import i10 from './generated/images/cul-a2-galerie-1080.webp';
import i11 from './generated/images/cul-a2-galerie-1600.webp';
import i12 from './generated/images/cul-a4-hero-320.webp';
import i13 from './generated/images/cul-a4-hero-640.webp';
import i14 from './generated/images/cul-a4-hero-1080.webp';
import i15 from './generated/images/cul-a4-hero-1600.webp';
import i16 from './generated/images/cul-a5-hero-320.webp';
import i17 from './generated/images/cul-a5-hero-640.webp';
import i18 from './generated/images/cul-a5-hero-1080.webp';
import i19 from './generated/images/cul-a5-hero-1600.webp';
import i20 from './generated/images/cul-a5-archives-320.webp';
import i21 from './generated/images/cul-a5-archives-640.webp';
import i22 from './generated/images/cul-a5-archives-1080.webp';
import i23 from './generated/images/cul-a5-archives-1600.webp';
import i24 from './generated/images/cul-a6-hero-320.webp';
import i25 from './generated/images/cul-a6-hero-640.webp';
import i26 from './generated/images/cul-a6-hero-1080.webp';
import i27 from './generated/images/cul-a6-hero-1600.webp';
import i28 from './generated/images/eco-a1-hero-320.webp';
import i29 from './generated/images/eco-a1-hero-640.webp';
import i30 from './generated/images/eco-a1-hero-1080.webp';
import i31 from './generated/images/eco-a1-hero-1600.webp';
import i32 from './generated/images/eco-a1-rassemblement-320.webp';
import i33 from './generated/images/eco-a1-rassemblement-640.webp';
import i34 from './generated/images/eco-a1-rassemblement-1080.webp';
import i35 from './generated/images/eco-a1-rassemblement-1600.webp';
import i36 from './generated/images/eco-a2-hero-320.webp';
import i37 from './generated/images/eco-a2-hero-640.webp';
import i38 from './generated/images/eco-a2-hero-1080.webp';
import i39 from './generated/images/eco-a2-hero-1600.webp';
import i40 from './generated/images/eco-a3-hero-320.webp';
import i41 from './generated/images/eco-a3-hero-640.webp';
import i42 from './generated/images/eco-a3-hero-1080.webp';
import i43 from './generated/images/eco-a3-hero-1600.webp';
import i44 from './generated/images/eco-a3-formation-320.webp';
import i45 from './generated/images/eco-a3-formation-640.webp';
import i46 from './generated/images/eco-a3-formation-1080.webp';
import i47 from './generated/images/eco-a3-formation-1600.webp';
import i48 from './generated/images/eco-a5-hero-320.webp';
import i49 from './generated/images/eco-a5-hero-640.webp';
import i50 from './generated/images/eco-a5-hero-1080.webp';
import i51 from './generated/images/eco-a5-hero-1600.webp';
import i52 from './generated/images/eco-a5-atelier-320.webp';
import i53 from './generated/images/eco-a5-atelier-640.webp';
import i54 from './generated/images/eco-a5-atelier-1080.webp';
import i55 from './generated/images/eco-a5-atelier-1600.webp';
import i56 from './generated/images/eco-a6-hero-320.webp';
import i57 from './generated/images/eco-a6-hero-640.webp';
import i58 from './generated/images/eco-a6-hero-1080.webp';
import i59 from './generated/images/eco-a6-hero-1600.webp';
import i60 from './generated/images/env-a1-hero-320.webp';
import i61 from './generated/images/env-a1-hero-640.webp';
import i62 from './generated/images/env-a1-hero-1080.webp';
import i63 from './generated/images/env-a1-hero-1600.webp';
import i64 from './generated/images/env-a1-retenue-320.webp';
import i65 from './generated/images/env-a1-retenue-640.webp';
import i66 from './generated/images/env-a1-retenue-1080.webp';
import i67 from './generated/images/env-a1-retenue-1600.webp';
import i68 from './generated/images/env-a2-hero-320.webp';
import i69 from './generated/images/env-a2-hero-640.webp';
import i70 from './generated/images/env-a2-hero-1080.webp';
import i71 from './generated/images/env-a2-hero-1600.webp';
import i72 from './generated/images/env-a3-hero-320.webp';
import i73 from './generated/images/env-a3-hero-640.webp';
import i74 from './generated/images/env-a3-hero-1080.webp';
import i75 from './generated/images/env-a3-hero-1600.webp';
import i76 from './generated/images/env-a3-observatoire-320.webp';
import i77 from './generated/images/env-a3-observatoire-640.webp';
import i78 from './generated/images/env-a3-observatoire-1080.webp';
import i79 from './generated/images/env-a3-observatoire-1600.webp';
import i80 from './generated/images/env-a4-hero-320.webp';
import i81 from './generated/images/env-a4-hero-640.webp';
import i82 from './generated/images/env-a4-hero-1080.webp';
import i83 from './generated/images/env-a4-hero-1600.webp';
import i84 from './generated/images/env-a4-cour-320.webp';
import i85 from './generated/images/env-a4-cour-640.webp';
import i86 from './generated/images/env-a4-cour-1080.webp';
import i87 from './generated/images/env-a4-cour-1600.webp';
import i88 from './generated/images/env-a5-hero-320.webp';
import i89 from './generated/images/env-a5-hero-640.webp';
import i90 from './generated/images/env-a5-hero-1080.webp';
import i91 from './generated/images/env-a5-hero-1600.webp';
import i92 from './generated/images/env-a6-hero-320.webp';
import i93 from './generated/images/env-a6-hero-640.webp';
import i94 from './generated/images/env-a6-hero-1080.webp';
import i95 from './generated/images/env-a6-hero-1600.webp';
import i96 from './generated/images/fem-a1-hero-320.webp';
import i97 from './generated/images/fem-a1-hero-640.webp';
import i98 from './generated/images/fem-a1-hero-1080.webp';
import i99 from './generated/images/fem-a1-hero-1600.webp';
import i100 from './generated/images/fem-a1-tournee-320.webp';
import i101 from './generated/images/fem-a1-tournee-640.webp';
import i102 from './generated/images/fem-a1-tournee-1080.webp';
import i103 from './generated/images/fem-a1-tournee-1600.webp';
import i104 from './generated/images/fem-a2-hero-320.webp';
import i105 from './generated/images/fem-a2-hero-640.webp';
import i106 from './generated/images/fem-a2-hero-1080.webp';
import i107 from './generated/images/fem-a2-hero-1600.webp';
import i108 from './generated/images/fem-a3-hero-320.webp';
import i109 from './generated/images/fem-a3-hero-640.webp';
import i110 from './generated/images/fem-a3-hero-1080.webp';
import i111 from './generated/images/fem-a3-hero-1600.webp';
import i112 from './generated/images/fem-a4-hero-320.webp';
import i113 from './generated/images/fem-a4-hero-640.webp';
import i114 from './generated/images/fem-a4-hero-1080.webp';
import i115 from './generated/images/fem-a4-hero-1600.webp';
import i116 from './generated/images/fem-a5-hero-320.webp';
import i117 from './generated/images/fem-a5-hero-640.webp';
import i118 from './generated/images/fem-a5-hero-1080.webp';
import i119 from './generated/images/fem-a5-hero-1600.webp';
import i120 from './generated/images/fem-a6-hero-320.webp';
import i121 from './generated/images/fem-a6-hero-640.webp';
import i122 from './generated/images/fem-a6-hero-1080.webp';
import i123 from './generated/images/fem-a6-hero-1600.webp';
import i124 from './generated/images/mon-a1-hero-320.webp';
import i125 from './generated/images/mon-a1-hero-640.webp';
import i126 from './generated/images/mon-a1-hero-1080.webp';
import i127 from './generated/images/mon-a1-hero-1600.webp';
import i128 from './generated/images/mon-a1-negociations-320.webp';
import i129 from './generated/images/mon-a1-negociations-640.webp';
import i130 from './generated/images/mon-a1-negociations-1080.webp';
import i131 from './generated/images/mon-a1-negociations-1600.webp';
import i132 from './generated/images/mon-a2-hero-320.webp';
import i133 from './generated/images/mon-a2-hero-640.webp';
import i134 from './generated/images/mon-a2-hero-1080.webp';
import i135 from './generated/images/mon-a2-hero-1600.webp';
import i136 from './generated/images/mon-a3-hero-320.webp';
import i137 from './generated/images/mon-a3-hero-640.webp';
import i138 from './generated/images/mon-a3-hero-1080.webp';
import i139 from './generated/images/mon-a3-hero-1600.webp';
import i140 from './generated/images/mon-a3-dockers-320.webp';
import i141 from './generated/images/mon-a3-dockers-640.webp';
import i142 from './generated/images/mon-a3-dockers-1080.webp';
import i143 from './generated/images/mon-a3-dockers-1600.webp';
import i144 from './generated/images/mon-a4-hero-320.webp';
import i145 from './generated/images/mon-a4-hero-640.webp';
import i146 from './generated/images/mon-a4-hero-1080.webp';
import i147 from './generated/images/mon-a4-hero-1600.webp';
import i148 from './generated/images/mon-a6-hero-320.webp';
import i149 from './generated/images/mon-a6-hero-640.webp';
import i150 from './generated/images/mon-a6-hero-1080.webp';
import i151 from './generated/images/mon-a6-hero-1600.webp';
import i152 from './generated/images/pol-a1-hero-320.webp';
import i153 from './generated/images/pol-a1-hero-640.webp';
import i154 from './generated/images/pol-a1-hero-1080.webp';
import i155 from './generated/images/pol-a1-hero-1600.webp';
import i156 from './generated/images/pol-a1-car-scolaire-320.webp';
import i157 from './generated/images/pol-a1-car-scolaire-640.webp';
import i158 from './generated/images/pol-a1-car-scolaire-1080.webp';
import i159 from './generated/images/pol-a1-car-scolaire-1600.webp';
import i160 from './generated/images/pol-a2-hero-320.webp';
import i161 from './generated/images/pol-a2-hero-640.webp';
import i162 from './generated/images/pol-a2-hero-1080.webp';
import i163 from './generated/images/pol-a2-hero-1600.webp';
import i164 from './generated/images/pol-a3-hero-320.webp';
import i165 from './generated/images/pol-a3-hero-640.webp';
import i166 from './generated/images/pol-a3-hero-1080.webp';
import i167 from './generated/images/pol-a3-hero-1600.webp';
import i168 from './generated/images/pol-a3-carte-fusion-320.webp';
import i169 from './generated/images/pol-a3-carte-fusion-640.webp';
import i170 from './generated/images/pol-a3-carte-fusion-1080.webp';
import i171 from './generated/images/pol-a3-carte-fusion-1600.webp';
import i172 from './generated/images/pol-a4-hero-320.webp';
import i173 from './generated/images/pol-a4-hero-640.webp';
import i174 from './generated/images/pol-a4-hero-1080.webp';
import i175 from './generated/images/pol-a4-hero-1600.webp';
import i176 from './generated/images/pol-a5-hero-320.webp';
import i177 from './generated/images/pol-a5-hero-640.webp';
import i178 from './generated/images/pol-a5-hero-1080.webp';
import i179 from './generated/images/pol-a5-hero-1600.webp';
import i180 from './generated/images/pol-a6-hero-320.webp';
import i181 from './generated/images/pol-a6-hero-640.webp';
import i182 from './generated/images/pol-a6-hero-1080.webp';
import i183 from './generated/images/pol-a6-hero-1600.webp';
import i184 from './generated/images/soc-a1-hero-320.webp';
import i185 from './generated/images/soc-a1-hero-640.webp';
import i186 from './generated/images/soc-a1-hero-1080.webp';
import i187 from './generated/images/soc-a1-hero-1600.webp';
import i188 from './generated/images/soc-a1-gymnase-320.webp';
import i189 from './generated/images/soc-a1-gymnase-640.webp';
import i190 from './generated/images/soc-a1-gymnase-1080.webp';
import i191 from './generated/images/soc-a1-gymnase-1600.webp';
import i192 from './generated/images/soc-a2-hero-320.webp';
import i193 from './generated/images/soc-a2-hero-640.webp';
import i194 from './generated/images/soc-a2-hero-1080.webp';
import i195 from './generated/images/soc-a2-hero-1600.webp';
import i196 from './generated/images/soc-a3-hero-320.webp';
import i197 from './generated/images/soc-a3-hero-640.webp';
import i198 from './generated/images/soc-a3-hero-1080.webp';
import i199 from './generated/images/soc-a3-hero-1600.webp';
import i200 from './generated/images/soc-a3-attente-320.webp';
import i201 from './generated/images/soc-a3-attente-640.webp';
import i202 from './generated/images/soc-a3-attente-1080.webp';
import i203 from './generated/images/soc-a3-attente-1600.webp';
import i204 from './generated/images/soc-a4-hero-320.webp';
import i205 from './generated/images/soc-a4-hero-640.webp';
import i206 from './generated/images/soc-a4-hero-1080.webp';
import i207 from './generated/images/soc-a4-hero-1600.webp';
import i208 from './generated/images/soc-a4-atelier-320.webp';
import i209 from './generated/images/soc-a4-atelier-640.webp';
import i210 from './generated/images/soc-a4-atelier-1080.webp';
import i211 from './generated/images/soc-a4-atelier-1600.webp';
import i212 from './generated/images/soc-a5-hero-320.webp';
import i213 from './generated/images/soc-a5-hero-640.webp';
import i214 from './generated/images/soc-a5-hero-1080.webp';
import i215 from './generated/images/soc-a5-hero-1600.webp';
import i216 from './generated/images/soc-a6-hero-320.webp';
import i217 from './generated/images/soc-a6-hero-640.webp';
import i218 from './generated/images/soc-a6-hero-1080.webp';
import i219 from './generated/images/soc-a6-hero-1600.webp';
import i220 from './generated/images/spo-a1-hero-320.webp';
import i221 from './generated/images/spo-a1-hero-640.webp';
import i222 from './generated/images/spo-a1-hero-1080.webp';
import i223 from './generated/images/spo-a1-hero-1600.webp';
import i224 from './generated/images/spo-a1-tribunes-320.webp';
import i225 from './generated/images/spo-a1-tribunes-640.webp';
import i226 from './generated/images/spo-a1-tribunes-1080.webp';
import i227 from './generated/images/spo-a1-tribunes-1600.webp';
import i228 from './generated/images/spo-a2-hero-320.webp';
import i229 from './generated/images/spo-a2-hero-640.webp';
import i230 from './generated/images/spo-a2-hero-1080.webp';
import i231 from './generated/images/spo-a2-hero-1600.webp';
import i232 from './generated/images/spo-a2-tribunes-320.webp';
import i233 from './generated/images/spo-a2-tribunes-640.webp';
import i234 from './generated/images/spo-a2-tribunes-1080.webp';
import i235 from './generated/images/spo-a2-tribunes-1600.webp';
import i236 from './generated/images/spo-a3-hero-320.webp';
import i237 from './generated/images/spo-a3-hero-640.webp';
import i238 from './generated/images/spo-a3-hero-1080.webp';
import i239 from './generated/images/spo-a3-hero-1600.webp';
import i240 from './generated/images/spo-a4-hero-320.webp';
import i241 from './generated/images/spo-a4-hero-640.webp';
import i242 from './generated/images/spo-a4-hero-1080.webp';
import i243 from './generated/images/spo-a4-hero-1600.webp';
import i244 from './generated/images/spo-a5-hero-320.webp';
import i245 from './generated/images/spo-a5-hero-640.webp';
import i246 from './generated/images/spo-a5-hero-1080.webp';
import i247 from './generated/images/spo-a5-hero-1600.webp';
import i248 from './generated/images/spo-a6-hero-320.webp';
import i249 from './generated/images/spo-a6-hero-640.webp';
import i250 from './generated/images/spo-a6-hero-1080.webp';
import i251 from './generated/images/spo-a6-hero-1600.webp';

/** The widths every picture is written at, narrowest first. */
export const ASSET_WIDTHS = [320, 640, 1080, 1600] as const;

/** One of the widths a picture is written at. */
export type AssetWidth = (typeof ASSET_WIDTHS)[number];

/** Every picture of the corpus, by key: the module the bundler resolves at each width. */
export const ASSETS: Readonly<Record<string, Readonly<Record<AssetWidth, number>>>> = {
  'cul-a1-hero': { 320: i0, 640: i1, 1080: i2, 1600: i3 },
  'cul-a2-hero': { 320: i4, 640: i5, 1080: i6, 1600: i7 },
  'cul-a2-galerie': { 320: i8, 640: i9, 1080: i10, 1600: i11 },
  'cul-a4-hero': { 320: i12, 640: i13, 1080: i14, 1600: i15 },
  'cul-a5-hero': { 320: i16, 640: i17, 1080: i18, 1600: i19 },
  'cul-a5-archives': { 320: i20, 640: i21, 1080: i22, 1600: i23 },
  'cul-a6-hero': { 320: i24, 640: i25, 1080: i26, 1600: i27 },
  'eco-a1-hero': { 320: i28, 640: i29, 1080: i30, 1600: i31 },
  'eco-a1-rassemblement': { 320: i32, 640: i33, 1080: i34, 1600: i35 },
  'eco-a2-hero': { 320: i36, 640: i37, 1080: i38, 1600: i39 },
  'eco-a3-hero': { 320: i40, 640: i41, 1080: i42, 1600: i43 },
  'eco-a3-formation': { 320: i44, 640: i45, 1080: i46, 1600: i47 },
  'eco-a5-hero': { 320: i48, 640: i49, 1080: i50, 1600: i51 },
  'eco-a5-atelier': { 320: i52, 640: i53, 1080: i54, 1600: i55 },
  'eco-a6-hero': { 320: i56, 640: i57, 1080: i58, 1600: i59 },
  'env-a1-hero': { 320: i60, 640: i61, 1080: i62, 1600: i63 },
  'env-a1-retenue': { 320: i64, 640: i65, 1080: i66, 1600: i67 },
  'env-a2-hero': { 320: i68, 640: i69, 1080: i70, 1600: i71 },
  'env-a3-hero': { 320: i72, 640: i73, 1080: i74, 1600: i75 },
  'env-a3-observatoire': { 320: i76, 640: i77, 1080: i78, 1600: i79 },
  'env-a4-hero': { 320: i80, 640: i81, 1080: i82, 1600: i83 },
  'env-a4-cour': { 320: i84, 640: i85, 1080: i86, 1600: i87 },
  'env-a5-hero': { 320: i88, 640: i89, 1080: i90, 1600: i91 },
  'env-a6-hero': { 320: i92, 640: i93, 1080: i94, 1600: i95 },
  'fem-a1-hero': { 320: i96, 640: i97, 1080: i98, 1600: i99 },
  'fem-a1-tournee': { 320: i100, 640: i101, 1080: i102, 1600: i103 },
  'fem-a2-hero': { 320: i104, 640: i105, 1080: i106, 1600: i107 },
  'fem-a3-hero': { 320: i108, 640: i109, 1080: i110, 1600: i111 },
  'fem-a4-hero': { 320: i112, 640: i113, 1080: i114, 1600: i115 },
  'fem-a5-hero': { 320: i116, 640: i117, 1080: i118, 1600: i119 },
  'fem-a6-hero': { 320: i120, 640: i121, 1080: i122, 1600: i123 },
  'mon-a1-hero': { 320: i124, 640: i125, 1080: i126, 1600: i127 },
  'mon-a1-negociations': { 320: i128, 640: i129, 1080: i130, 1600: i131 },
  'mon-a2-hero': { 320: i132, 640: i133, 1080: i134, 1600: i135 },
  'mon-a3-hero': { 320: i136, 640: i137, 1080: i138, 1600: i139 },
  'mon-a3-dockers': { 320: i140, 640: i141, 1080: i142, 1600: i143 },
  'mon-a4-hero': { 320: i144, 640: i145, 1080: i146, 1600: i147 },
  'mon-a6-hero': { 320: i148, 640: i149, 1080: i150, 1600: i151 },
  'pol-a1-hero': { 320: i152, 640: i153, 1080: i154, 1600: i155 },
  'pol-a1-car-scolaire': { 320: i156, 640: i157, 1080: i158, 1600: i159 },
  'pol-a2-hero': { 320: i160, 640: i161, 1080: i162, 1600: i163 },
  'pol-a3-hero': { 320: i164, 640: i165, 1080: i166, 1600: i167 },
  'pol-a3-carte-fusion': { 320: i168, 640: i169, 1080: i170, 1600: i171 },
  'pol-a4-hero': { 320: i172, 640: i173, 1080: i174, 1600: i175 },
  'pol-a5-hero': { 320: i176, 640: i177, 1080: i178, 1600: i179 },
  'pol-a6-hero': { 320: i180, 640: i181, 1080: i182, 1600: i183 },
  'soc-a1-hero': { 320: i184, 640: i185, 1080: i186, 1600: i187 },
  'soc-a1-gymnase': { 320: i188, 640: i189, 1080: i190, 1600: i191 },
  'soc-a2-hero': { 320: i192, 640: i193, 1080: i194, 1600: i195 },
  'soc-a3-hero': { 320: i196, 640: i197, 1080: i198, 1600: i199 },
  'soc-a3-attente': { 320: i200, 640: i201, 1080: i202, 1600: i203 },
  'soc-a4-hero': { 320: i204, 640: i205, 1080: i206, 1600: i207 },
  'soc-a4-atelier': { 320: i208, 640: i209, 1080: i210, 1600: i211 },
  'soc-a5-hero': { 320: i212, 640: i213, 1080: i214, 1600: i215 },
  'soc-a6-hero': { 320: i216, 640: i217, 1080: i218, 1600: i219 },
  'spo-a1-hero': { 320: i220, 640: i221, 1080: i222, 1600: i223 },
  'spo-a1-tribunes': { 320: i224, 640: i225, 1080: i226, 1600: i227 },
  'spo-a2-hero': { 320: i228, 640: i229, 1080: i230, 1600: i231 },
  'spo-a2-tribunes': { 320: i232, 640: i233, 1080: i234, 1600: i235 },
  'spo-a3-hero': { 320: i236, 640: i237, 1080: i238, 1600: i239 },
  'spo-a4-hero': { 320: i240, 640: i241, 1080: i242, 1600: i243 },
  'spo-a5-hero': { 320: i244, 640: i245, 1080: i246, 1600: i247 },
  'spo-a6-hero': { 320: i248, 640: i249, 1080: i250, 1600: i251 },
};
