import { mkdirSync, writeFileSync } from 'node:fs';
import { buildCorpus } from './build.ts';

/** Writes the validated corpus as static data the app can import without a markdown parser. */
const directory = new URL('./generated/', import.meta.url);
mkdirSync(directory, { recursive: true });
const corpus = buildCorpus();
const source = [
  '// @generated by `pnpm --filter @huma/mock-content generate` — do not edit by hand.',
  '',
  `export const CORPUS_DATA = ${JSON.stringify(corpus, null, 2)};`,
  '',
].join('\n');
writeFileSync(new URL('corpus.ts', directory), source);
process.stdout.write(`corpus : ${String(corpus.length)} items générés\n`);
