import type { CorpusArticle } from './item.ts';
import { VISUAL_WIDTHS } from './artwork.ts';
import { buildCorpus } from './build.ts';
import { codeOf } from './registries.ts';
import { imageName, renderVisual } from './render.ts';
import type { Visual } from './render.ts';
import { imageKeys } from './validate.ts';

/** The header every generated module carries, so a hand edit is visibly wrong. */
const GENERATED = '// @generated by `pnpm corpus:generate` — do not edit by hand.';

/**
 * What one run wrote, and the modules it hands back to be formatted and written: where each goes, and what it holds
 * before the repository's formatter sets it.
 */
export type GeneratedCorpus = Readonly<{
  items: number;
  pictures: number;
  files: number;
  modules: readonly Readonly<{ url: URL; text: string }>[];
}>;

/**
 * The corpus as static data the app can import without a markdown parser. It is set the French way, and its
 * unbreakable spaces are written as escapes: JSON leaves the character as it is, and a generated module is still a
 * source a reader opens — one whose blanks would not all be the blanks they look like.
 */
const corpusModule = (corpus: readonly CorpusArticle[]): string => {
  const data = JSON.stringify(corpus, null, 2).replaceAll('\u00A0', '\\u00A0');
  return [GENERATED, '', `export const CORPUS_DATA = ${data};`, ''].join('\n');
};

/** The placeholder painted while each picture of the corpus loads, by key. */
const visualsModule = (visuals: readonly Visual[]): string =>
  [
    GENERATED,
    '',
    '/** The placeholder painted while each picture of the corpus loads, by key. */',
    `export const VISUALS: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(visuals.map(({ key, thumbhash }) => [key, thumbhash])), null, 2)};`,
    '',
  ].join('\n');

/**
 * The registry that puts the written pictures in the bundle. Metro reads an asset specifier at build time, so each
 * width needs its own static import; the bindings are numbered rather than named after their key because the spell
 * checker reads identifiers and the keys are French nouns, while the keys themselves stay strings, which it never reads.
 */
const assetsModule = (visuals: readonly Visual[]): string => {
  const binding = (index: number, offset: number): string => `i${String(index * VISUAL_WIDTHS.length + offset)}`;
  const imports = visuals.flatMap(({ key }, index) =>
    VISUAL_WIDTHS.map(
      (width, offset) => `import ${binding(index, offset)} from './generated/images/${imageName(key, width)}';`,
    ),
  );
  const entries = visuals.map(({ key }, index) => {
    const widths = VISUAL_WIDTHS.map((width, offset) => `${String(width)}: ${binding(index, offset)}`);
    return `  '${key}': { ${widths.join(', ')} },`;
  });
  return [
    GENERATED,
    '',
    ...imports,
    '',
    '/** The widths every picture is written at, narrowest first. */',
    `export const ASSET_WIDTHS = [${VISUAL_WIDTHS.join(', ')}] as const;`,
    '',
    '/** One of the widths a picture is written at. */',
    'export type AssetWidth = (typeof ASSET_WIDTHS)[number];',
    '',
    '/** Every picture of the corpus, by key: the module the bundler resolves at each width. */',
    'export const ASSETS: Readonly<Record<string, Readonly<Record<AssetWidth, number>>>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
};

/**
 * Builds the corpus from its sources, writes the picture that stands in for each illustration it names, and hands back
 * the three modules that put both in the app. The modules come back unformatted and unwritten: setting them the way
 * the repository sets every file is its formatter's to do, and only the tools reach it.
 */
export async function generateCorpus(): Promise<GeneratedCorpus> {
  const corpus = buildCorpus();
  const visuals: Visual[] = [];
  for (const article of corpus) {
    const code = codeOf(article.section);
    if (code === undefined) {
      throw new RangeError(`${article.id} : rubrique inconnue du corpus`);
    }
    for (const key of imageKeys(article)) {
      visuals.push(await renderVisual(key, code));
    }
  }
  return {
    items: corpus.length,
    pictures: visuals.length,
    files: visuals.length * VISUAL_WIDTHS.length,
    modules: [
      { url: new URL('./generated/corpus.ts', import.meta.url), text: corpusModule(corpus) },
      { url: new URL('./generated/visuals.ts', import.meta.url), text: visualsModule(visuals) },
      { url: new URL('./assets.ts', import.meta.url), text: assetsModule(visuals) },
    ],
  };
}
