import { mkdirSync, writeFileSync } from 'node:fs';
import { sectionCode } from '@huma/design-tokens';
import { buildCorpus } from './build.ts';
import { SECTIONS } from './registries.ts';
import { renderVisual } from './render.ts';
import type { Visual } from './render.ts';
import { imageKeys } from './validate.ts';

/** Writes the validated corpus as static data the app can import without a markdown parser. */
const directory = new URL('./generated/', import.meta.url);
mkdirSync(directory, { recursive: true });
const corpus = buildCorpus();
const source = [
  '// @generated by `pnpm --filter @huma/mock-content generate` — do not edit by hand.',
  '',
  `export const CORPUS_DATA = ${JSON.stringify(corpus, null, 2)};`,
  '',
].join('\n');
writeFileSync(new URL('corpus.ts', directory), source);
process.stdout.write(`corpus : ${String(corpus.length)} items générés\n`);

/** Then the picture that stands in for each illustration the mock has no photograph for. */
const visuals: Visual[] = [];
for (const article of corpus) {
  const section = SECTIONS.find((each) => each.id === article.section);
  const code = sectionCode(section?.code ?? '');
  for (const key of imageKeys(article)) {
    visuals.push(await renderVisual(key, code));
  }
}
const manifest = [
  '// @generated by `pnpm --filter @huma/mock-content generate` — do not edit by hand.',
  '',
  `export const VISUALS = ${JSON.stringify(Object.fromEntries(visuals.map(({ key, thumbhash }) => [key, thumbhash])), null, 2)};`,
  '',
].join('\n');
writeFileSync(new URL('visuals.ts', directory), manifest);
process.stdout.write(`visuels : ${String(visuals.length)} clés, ${String(visuals.length * 4)} fichiers écrits\n`);
