import type { Bindings } from '@huma/adr/bindings';
import { repoPath } from '@huma/kit/paths';
import type { ProofId } from './proofs.ts';

/** Where the bindings live, as the index and the diagnostics name them. */
export const BINDINGS_PATH = repoPath('tools/governance/src/bindings.ts');

/**
 * How each binding rule of each ADR is proven, and what each ADR governs. ADR files are frozen once decided; this file
 * follows the code instead, and `adr:check` keeps it in step with the rules written in the ADRs.
 */
export const BINDINGS = {
  'ADR-0000': {
    scope: {
      paths: [
        'docs/adr/**',
        'tools/adr/**',
        'tools/agents/src/guard.ts',
        'tools/governance/src/acknowledgments.ts',
        'tools/governance/src/bindings.ts',
        'tools/governance/src/bindings-file.ts',
        'tools/governance/src/cli/adr-check.ts',
        'tools/governance/src/cli/adr-decide.ts',
        'tools/governance/src/cli/adr-new.ts',
        'tools/governance/src/cli/adr-status.ts',
        'tools/governance/src/commit-refs.ts',
        'tools/governance/src/decision.ts',
        'tools/governance/src/proofs/commit-refs.ts',
        'tools/governance/src/workspace.ts',
      ],
    },
    rules: {
      R1: [
        'adr/valid',
        'adr/valid-words-limit',
        'adr/valid-nbsp',
        'adr/valid-link-target',
        'adr/valid-root-link-target',
        'adr/encoding-invalid-utf8',
        'adr/encoding-bom',
        'adr/encoding-not-nfc',
        'adr/encoding-invisible',
        'adr/encoding-invisible-crlf',
        'adr/frontmatter-missing',
        'adr/frontmatter-yaml',
        'adr/frontmatter-schema',
        'adr/frontmatter-not-canonical',
        'adr/frontmatter-not-canonical-delimiter',
        'adr/markdown-node',
        'adr/markdown-heading-depth',
        'adr/markdown-task-list',
        'adr/markdown-link-title',
        'adr/markdown-indented-code',
        'adr/markdown-code-language',
        'adr/title-missing',
        'adr/title-not-first',
        'adr/title-duplicate',
        'adr/title-rich',
        'adr/title-no-letter',
        'adr/title-too-long',
        'adr/title-forbidden-character',
        'adr/title-final-punctuation',
        'adr/slug-mismatch',
        'adr/section-content-before',
        'adr/section-order',
        'adr/section-subsection',
        'adr/section-consequences',
        'adr/section-pros-and-cons-text',
        'adr/words-limit',
        'adr/link-scheme',
        'adr/link-malformed',
        'adr/link-empty',
        'adr/link-scheme-protocol-relative',
        'adr/link-target-missing',
        'adr/mention-malformed',
        'adr/mention-unknown',
        'adr/path-directory',
        'adr/path-name',
        'new/title-refused',
      ],
      R2: ['adr/frontmatter-format-unknown', 'adr/frontmatter-format-outdated', 'adr/format-regression'],
      R3: [
        'adr/context-question-missing',
        'adr/context-question-shape',
        'adr/valid-question-code',
        'adr/context-facts-missing',
        'adr/context-fact-shape',
        'adr/context-fact-unsourced',
        'adr/context-fact-fragment-only',
        'adr/context-stray-block',
        'adr/criteria-list',
        'adr/criteria-label',
        'adr/options-list',
        'adr/options-name',
        'adr/options-duplicate',
        'adr/options-too-few',
        'adr/options-subsections',
        'adr/decision-chosen-shape',
        'adr/decision-chosen-unknown',
        'adr/decision-chosen-duplicate',
        'adr/decision-rules-missing',
        'adr/decision-rule-label',
        'adr/decision-trailing-block',
        'adr/decision-no-binding-rule',
        'adr/argument-list',
        'adr/argument-shape',
        'adr/consequences-balance',
        'adr/option-chosen-without-good',
        'adr/option-rejected-without-bad',
        'adr/citation-malformed',
        'adr/citation-unknown',
        'adr/citation-chosen-missing',
        'adr/citation-argument-missing',
        'adr/citation-criterion-unused',
        'adr/reevaluation-list',
        'adr/reevaluation-count',
      ],
      R4: [
        'adr/keyword-forbidden',
        'adr/keyword-forbidden-unaccented',
        'adr/keyword-negation',
        'adr/keyword-negation-may',
        'adr/keyword-negation-without-ne',
        'adr/keyword-forbidden-hyphenated',
        'adr/keyword-count',
        'adr/keyword-outside-rule',
      ],
      R5: [
        'adr/number-duplicate',
        'adr/deleted',
        'adr/number-reused',
        'adr/valid-restored',
        'adr/number-duplicate-keeps-lineage',
        'new/parallel-worktrees',
        'new/unreserved-race',
        'new/reserved-number-skipped',
        'new/parallel-creations',
        'new/abandoned-number-kept',
      ],
      R6: [
        'adr/transition-first-not-proposed',
        'adr/transition-forbidden',
        'adr/transition-uncommitted',
        'decide/failing-checks-refused',
        'decide/unknown-adr-refused',
        'decide/stale-artifacts-refused',
        'decide/concurrent-change-refused',
        'decide/failing-result-undone',
        'decide/dirty-tree-refused',
        'decide/already-decided-refused',
        'adr/valid-merge-acceptance',
        'adr/decision-content-changed',
        'adr/decision-content-changed-staged',
        'decide/rejects',
        'decide/valid-message-accepted',
        'decide/valid-message-superseding',
      ],
      R7: [
        'adr/frozen-modified',
        'adr/frozen-after-unreadable',
        'adr/frozen-renamed',
        'adr/history-shallow',
        'adr/history-not-repository',
        'adr/valid-accepted',
        'adr/valid-code-block-status',
        'guard/decided-write',
        'format/prettier-keeps-fingerprint',
        'format/embedded-code-changes-fingerprint',
      ],
      R8: [
        'agent/decide-script',
        'agent/decide-run-script',
        'agent/decide-entry',
        'agent/decide-masked-session',
        'agent/decide-in-subshell',
        'agent/decide-in-substitution',
        'agent/decide-monitor',
        'agent/decide-relative-entry',
        'agent/decide-exec-runner',
        'agent/decide-eval-code',
        'agent/decide-mentioned',
        'agent/decide-source-read',
        'agent/adr-check',
        'agent/unset-session',
        'agent/empty-session',
        'agent/unexport-session',
        'agent/ignore-environment',
        'agent/status-edit',
        'agent/decided-edit',
        'agent/decided-multi-edit',
        'agent/proposed-edit-missing-text',
        'agent/relative-status-write',
        'agent/shell-sed-status',
        'agent/shell-sed-proposed',
        'agent/shell-cd-relative',
        'agent/shell-loop-pattern',
        'agent/shell-heredoc-decided',
        'agent/shell-append-decided',
        'agent/shell-remove-decided',
        'agent/shell-remove-proposed',
        'agent/shell-rename-decided',
        'agent/shell-copy-decided',
        'agent/shell-remove-tree',
        'agent/shell-find-delete',
        'agent/shell-find-refactor',
        'agent/shell-symlink-decided',
        'agent/write-outside',
        'agent/write-settings',
        'agent/write-local-settings',
        'agent/write-through-symlink',
        'agent/shell-local-settings',
        'agent/shell-home-settings',
        'agent/shell-tee-settings',
        'agent/unreadable-input',
        'agent/input-without-tool',
        'agent/shell-without-command',
        'agent/write-without-path',
        'agent/code-sensitive',
        'agent/code-innocuous',
        'agent/other-tool',
        'agent/valid-no-local-settings',
        'agent/valid-local-permissions',
        'agent/local-settings-hooks-disabled',
        'agent/local-settings-unreadable',
        'guard/status-change',
        'guard/new-decided-file',
        'guard/new-skeleton',
        'guard/tagged-status',
        'guard/escaped-status',
        'guard/non-canonical-proposed',
        'guard/escaped-decided-rewrite',
        'guard/unknown-result',
        'decide/agent-refused',
        'adr/decision-by-agent',
        'adr/decision-by-agent-worktree',
        'adr/valid-agent-merges-human-decision',
        'claude-hook/settings-command-denies',
        'claude-hook/settings-command-allows',
        'claude-hook/failure-denies-sensitive',
        'claude-hook/failure-allows-innocuous',
      ],
      R9: [
        'adr/binding-malformed-id',
        'adr/binding-unknown-adr',
        'adr/binding-inactive',
        'adr/binding-missing',
        'adr/binding-rule-unbound',
        'adr/binding-rule-extra',
        'adr/valid-optional-binding',
        'adr/binding-optional-only',
        'adr/binding-convention-empty',
        'adr/binding-proof-unknown',
        'adr/binding-no-proven-rule',
        'adr/scope-glob-invalid',
        'adr/scope-glob-duplicate',
        'adr/scope-glob-empty',
        'adr/accept-proof-failing',
        'adr/valid-staged-acceptance',
        'decide/failing-proof-refused',
        'decide/unbound-acceptance-refused',
        'decide/accepts',
      ],
      R10: ['gen/stale-index', 'gen/missing-index', 'gen/in-step'],
      R11: [
        'adr/supersedes-unknown',
        'adr/supersedes-newer',
        'adr/supersedes-not-accepted',
        'adr/supersedes-several',
        'adr/valid-superseded',
        'adr/decision-supersedes-added',
        'decide/accepts-superseding',
      ],
      R12: [
        'adr/valid-acknowledged',
        'adr/acknowledgment-unused',
        'adr/valid-frozen-acknowledged',
        'adr/frozen-acknowledged-then-edited',
      ],
      R13: [
        'adr/valid-history',
        'adr/valid-renamed-proposed',
        'guard/proposed-edit',
        'agent/proposed-edit',
        'agent/proposed-edit-straight-quotes',
        'agent/shell-heredoc-proposed',
        'agent/shell-rename-proposed',
        'agent/shell-copy-proposed',
      ],
    },
  },
  'ADR-0001': {
    scope: {
      paths: [
        'pnpm-workspace.yaml',
        'pnpm-lock.yaml',
        'package.json',
        'apps/*/package.json',
        'packages/*/package.json',
        'tools/*/package.json',
        'tools/deps/**',
        'tools/governance/src/cli/deps-check.ts',
      ],
    },
    rules: {
      R1: [
        'deps/catalog-missing',
        'deps/catalog-stale',
        'deps/catalog-unused',
        'deps/single-version',
        'deps/lockfile-version',
      ],
      R2: [
        'deps/catalog-range',
        'deps/sibling-version',
        'deps/single-instance',
        'deps/importer-stale',
        'deps/importer-missing',
        'deps/importer-extra',
        'deps/importer-unknown',
        'deps/private-copy',
        'deps/private-copy-allowed',
        'deps/private-copy-unused',
      ],
      R3: ['deps/tested-version', 'deps/untested-version'],
      R4: ['deps/specifier-form'],
      R5: ['deps/root-unknown', 'deps/root-dependency'],
      R6: ['deps/peer-undeclared'],
      R7: ['deps/policy-unknown'],
    },
  },
  'ADR-0002': {
    scope: {
      paths: [
        'apps/mobile/app.config.ts',
        'apps/mobile/app/**',
        'tools/expo/**',
        'tools/governance/src/cli/expo-types.ts',
      ],
    },
    rules: {
      R1: ['deps/tested-version', 'deps/untested-version'],
      R2: [
        'expo/routes-directory',
        'expo/tsconfig-rewrite',
        'expo/gitignore-rewrite',
        'expo/routes-invalid',
        'expo/typed-routes',
      ],
      R3: {
        convention:
          'Les invariants d’app.config sont vérifiés par tools/expo/src/app-config.test.ts, hors du banc de fixtures.',
      },
      R4: [
        'guardrail/hermes-array-from-async',
        'guardrail/hermes-array-to-sorted',
        'guardrail/hermes-crypto-get-random-values',
        'guardrail/hermes-crypto-random-uuid',
        'guardrail/hermes-finalization-registry',
        'guardrail/hermes-intl-display-names',
        'guardrail/hermes-intl-format-range',
        'guardrail/hermes-intl-list-format',
        'guardrail/hermes-intl-locale',
        'guardrail/hermes-intl-plural-rules',
        'guardrail/hermes-intl-plural-rules-destructured',
        'guardrail/hermes-intl-plural-rules-global-this',
        'guardrail/hermes-intl-relative-time-format',
        'guardrail/hermes-intl-segmenter',
        'guardrail/hermes-intl-supported-values-of',
        'guardrail/hermes-iterator-helpers',
        'guardrail/hermes-map-group-by',
        'guardrail/hermes-object-group-by',
        'guardrail/hermes-regexp-escape',
        'guardrail/hermes-regexp-v-flag',
        'guardrail/hermes-regexp-v-flag-call',
        'guardrail/hermes-regexp-v-flag-constructor',
        'guardrail/hermes-temporal',
        'guardrail/hermes-temporal-global-this',
      ],
    },
  },
  'ADR-0003': {
    scope: {
      paths: [
        'packages/tsconfig/**',
        'tsconfig.json',
        'apps/*/tsconfig.json',
        'packages/*/tsconfig.json',
        'tools/*/tsconfig.json',
        'tools/governance/src/tsconfig-snapshot.ts',
      ],
    },
    rules: {
      R1: ['deps/single-instance', 'deps/single-version'],
      R2: {
        convention:
          'Les options strictes de chaque projet sont vérifiées par tools/governance/src/tsconfig-snapshot.test.ts contre le préréglage packages/tsconfig/strict.json.',
      },
      R3: ['guardrail/node-import-js', 'guardrail/node-export-js', 'guardrail/node-dynamic-import-js'],
      R4: ['guardrail/node-decorator', 'guardrail/node-accessor'],
      R5: ['deps/reference-missing', 'deps/reference-undeclared'],
      R6: ['guardrail/node-process-exit'],
    },
  },
  'ADR-0004': {
    scope: {
      paths: [
        'packages/eslint-config/**',
        'tools/lint/**',
        'tools/governance/src/cli/lint.ts',
        'tools/governance/src/cli/format.ts',
        'tools/guardrails/src/effective-config.test.ts',
      ],
    },
    rules: {
      R1: ['lint/rule', 'lint/unconfigured', 'lint/parse-error', 'lint/git-ignored', 'lint/clean'],
      R2: ['lint/inline-config', 'lint/suppressed', 'lint/suppressions-file'],
      R3: ['lint/unformatted', 'lint/format-error', 'lint/prettier-ignored'],
      R4: {
        convention:
          'L’absence d’avertissement et le maintien à error des bans typés nommés sont vérifiés par tools/guardrails/src/effective-config.test.ts.',
      },
      R5: ['lint/deprecated-rule'],
    },
  },
  'ADR-0005': {
    scope: {
      paths: [
        'apps/mobile/app/**',
        'apps/mobile/src/**',
        'packages/architecture/**',
        'tools/structure/**',
        'tools/governance/src/cli/structure-check.ts',
      ],
    },
    rules: {
      R1: [
        'structure/ambiguous-slice-names',
        'structure/inconsistent-naming',
        'structure/insignificant-slice',
        'structure/no-reserved-folder-names',
        'structure/repetitive-naming',
        'structure/excessive-slicing',
        'structure/shared-lib-grouping',
        'structure/import-locality',
        'structure/clean',
      ],
      R2: ['guardrail/place-unknown-file', 'guardrail/unknown-file-imports'],
      R3: ['guardrail/entry-re-export', 'guardrail/export-all'],
      R4: ['structure/cycle', 'structure/cycle-in-routes'],
      R5: ['guardrail/route-re-export', 'guardrail/route-error-boundary'],
    },
  },
  'ADR-0006': {
    scope: {
      paths: ['packages/architecture/**', 'packages/eslint-config/src/index.ts'],
    },
    rules: {
      R1: [
        'guardrail/import-primitive',
        'guardrail/import-component',
        'guardrail/import-entity',
        'guardrail/import-feature',
        'guardrail/import-page',
        'guardrail/import-app',
        'guardrail/import-route',
        'guardrail/import-api',
        'guardrail/import-config',
        'guardrail/import-i18n',
        'guardrail/import-lib',
      ],
      R2: ['guardrail/import-page-internals'],
      R3: [
        'guardrail/module-react-native',
        'guardrail/module-react-native-entry',
        'guardrail/module-react-native-platform',
        'guardrail/module-react-native-namespace',
        'guardrail/module-react-native-gesture-handler',
        'guardrail/module-react-native-reanimated',
        'guardrail/module-react-native-safe-area-context',
        'guardrail/module-react-native-screens',
      ],
      R4: ['guardrail/platform-variant', 'guardrail/platform-variant-primitive'],
    },
  },
  'ADR-0007': {
    scope: {
      paths: [
        'packages/architecture/src/glossary.ts',
        'packages/eslint-config/src/spelling.ts',
        'packages/eslint-config/cspell.json',
      ],
    },
    rules: {
      R1: ['guardrail/spelling-unknown'],
      R2: [
        'guardrail/glossary-term',
        'guardrail/glossary-synonym',
        'lint/glossary-word-inside',
        'lint/glossary-file-name',
      ],
      R3: [
        'guardrail/naming-file',
        'guardrail/naming-folder',
        'guardrail/naming-route-conventions',
        'guardrail/naming-route-file',
        'guardrail/naming-route-folder',
      ],
    },
  },
  'ADR-0008': {
    scope: {
      paths: [
        'tools/git-hooks/**',
        'tools/fixtures/**',
        'tools/governance/src/cli/git-hook.ts',
        'tools/governance/src/cli/hooks-check.ts',
        'tools/governance/src/cli/hooks-install.ts',
      ],
    },
    rules: {
      R1: [
        'git/header',
        'git/header-length',
        'git/type',
        'git/scope',
        'git/scope-before-package',
        'git/body-separator',
        'git/not-canonical',
        'git/generated-fixup',
        'git/generated-message',
        'git/breaking-change-space',
        'git/comment-line',
        'git/control-character',
        'git/valid-message',
      ],
      R2: [
        'git/refs-missing',
        'git/refs-missing-commit-msg',
        'git/refs-format',
        'git/refs-order',
        'git/refs-extra',
        'git/refs-in-prose',
        'git/refs-unrelated-cited',
        'git/refs-scope-required',
        'git/refs-adr-file-required',
        'git/trailer-unknown',
      ],
      R3: [
        'git/hook-missing',
        'git/hook-modified',
        'git/hook-not-executable',
        'git/hook-unexpected',
        'git/hooks-directory-link',
        'git/hooks-path',
        'git/hooks-path-worktree',
        'git/install-refused-hooks-path',
        'git/config-include',
        'git/no-verify-through-shims',
        'git/valid-installation',
        'git/valid-commit-through-shims',
      ],
      R4: [
        'git/verify-failed',
        'git/verify-skipped',
        'git/verify-skipped-index-changed',
        'git/verify-skipped-marker-forged',
        'git/verify-skipped-marker-reused',
        'git/tree-changed',
        'git/index-flagged',
        'git/unstaged',
        'git/unstaged-before-checks',
        'git/untracked',
        'git/unmerged',
        'git/valid-pre-commit',
        'git/valid-staging',
        'git/valid-verified-tree',
      ],
      R5: {
        convention:
          'Le banc de fixtures de tools/fixtures et les tests de couverture et de mutation de chaque liste de preuves prouvent que chaque garde-fou se déclenche exactement sur ses codes.',
      },
      R6: [
        'git/history-bypassed-commit',
        'git/history-replaced-commit',
        'git/patch-refused',
        'git/anchor-not-ancestor',
        'git/anchor-unknown',
        'git/history-shallow',
      ],
    },
  },
  'ADR-0009': {
    scope: {
      paths: ['tools/agents/**'],
    },
    rules: {
      R1: [
        'agent/sudo',
        'agent/sudo-absolute-path',
        'agent/sudo-substituted-name',
        'agent/sudo-wrapped',
        'agent/su-command',
        'agent/chroot',
        'agent/setarch-hides-sudo',
        'agent/systemd-run-root',
      ],
      R2: [
        'agent/no-verify',
        'agent/no-verify-abbreviated',
        'agent/no-verify-ansi-quoted',
        'agent/no-verify-braces',
        'agent/no-verify-find-exec',
        'agent/no-verify-function',
        'agent/no-verify-heredoc-shell',
        'agent/no-verify-ifs',
        'agent/no-verify-split-string',
        'agent/no-verify-unknown-subcommand',
        'agent/no-verify-variable',
        'agent/am-no-verify',
        'agent/cherry-pick-no-verify',
        'agent/merge-no-verify',
        'agent/pull-no-verify',
        'agent/push-no-verify',
        'agent/rebase-no-verify',
        'agent/revert-no-verify',
        'agent/grep-no-verify',
        'agent/hooks-directory',
        'agent/hooks-path-config',
        'agent/hooks-path-option',
        'agent/hooks-path-read',
        'agent/include-path-config',
        'agent/include-path-option',
        'agent/shell-chmod-hook',
      ],
      R3: ['agent/edit-git-config', 'agent/git-dir-variable', 'agent/git-index-variable', 'agent/git-absolute-path'],
      R4: [
        'agent/emulator-compose',
        'agent/emulator-compose-tool',
        'agent/emulator-container-command',
        'agent/emulator-exec',
        'agent/emulator-image',
        'agent/emulator-inspect',
        'agent/emulator-nerdctl',
        'agent/emulator-network',
        'agent/emulator-podman',
        'agent/emulator-remove',
        'agent/emulator-run',
        'agent/emulator-runtime',
        'agent/emulator-script',
        'agent/emulator-volume',
      ],
      R5: ['agent/verify-stamp-forged'],
    },
  },
  'ADR-0010': {
    scope: {
      paths: ['tools/emulator/**'],
    },
    rules: {
      R1: [
        'emulator/image-absent',
        'emulator/image-untagged',
        'emulator/valid-image',
        'emulator/container-other-options',
        'emulator/valid-container',
      ],
      R2: ['emulator/binder-device-mode', 'emulator/binder-unloaded', 'emulator/valid-binder'],
      R3: [
        'emulator/guard-installed-uncommitted',
        'emulator/guard-not-armed',
        'emulator/guard-run-stale',
        'emulator/guard-scripts-changed',
        'emulator/valid-guard',
        'root/run-scripts-changed',
        'root/arm-residue',
      ],
      R4: [
        'emulator/host-drift-session',
        'emulator/host-residue-left',
        'emulator/valid-clean-host',
        'root/run-boot-restored',
        'root/run-boot-keeps-writing',
        'root/run-stop-instance',
        'root/repair-clean-values',
        'root/run-idle-follows',
        'root/run-idle-neighbor',
        'root/run-capture-failed',
        'root/run-docker-unreadable',
        'root/run-empty-values',
        'root/run-filesystem-before-mount-point',
        'root/run-unwritable',
        'root/run-write-failed',
      ],
      R5: [
        'root/plan-any-tracefs-mode',
        'root/plan-appeared-entry',
        'root/plan-idle-android',
        'root/plan-idle-neighbor',
        'root/plan-idle-unvalued-kind',
        'root/plan-instance-running',
        'root/plan-instance-stopped',
        'root/plan-known-attributes',
        'root/plan-known-sysctl',
        'root/plan-multiline',
        'root/plan-other-value',
        'root/plan-unknown-instance',
        'root/plan-unknown-sysctl',
        'root/plan-volatile',
      ],
    },
  },
  'ADR-0011': {
    scope: {
      paths: ['packages/contracts/**'],
    },
    rules: {
      R1: {
        convention:
          'Les types, erreurs et identifiants de données sont définis par des schémas Zod dans packages/contracts, que les autres paquets réemploient.',
      },
      R2: ['deps/dependency-confined'],
      R3: {
        convention:
          'La sortie brandée d’un schéma Zod n’est pas assignable depuis une chaîne : seule l’analyse d’un schéma des contrats produit un identifiant.',
      },
    },
  },
  'ADR-0012': {
    scope: {
      paths: ['packages/design-tokens/**', 'apps/mobile/src/shared/lib/styles/**'],
    },
    rules: {
      R1: {
        convention:
          'Le type Style de apps/mobile/src/shared/lib/styles n’accepte comme valeur dimensionnelle ou colorée qu’un token brandé de @huma/design-tokens, hors de portée d’un nombre ou d’une chaîne bruts.',
      },
      R2: {
        convention:
          'La prop style d’une primitive est typée StyleRef, la marque opaque que seule createStyles produit ; un objet de style quelconque n’y est pas assignable.',
      },
      R3: [
        'guardrail/style-inline',
        'guardrail/style-inline-array',
        'guardrail/style-inline-named',
        'guardrail/style-inline-nested',
      ],
      R4: ['guardrail/style-theme', 'guardrail/style-theme-exempt'],
    },
  },
  'ADR-0013': {
    scope: {
      paths: [
        'packages/contracts/src/display-text.ts',
        'apps/mobile/src/shared/i18n/**',
        'apps/mobile/src/shared/lib/display-text/**',
        'apps/mobile/src/shared/lib/format/**',
        'apps/mobile/src/shared/ui/primitives/text/**',
      ],
    },
    rules: {
      R1: ['guardrail/text-mint', 'guardrail/text-mint-reexport'],
      R2: {
        convention:
          'Le texte qu’une primitive de texte reçoit est typé DisplayText, la marque opaque des contrats, qu’il entre par children ou par les fragments d’une phrase ; une chaîne quelconque n’y est pas assignable.',
      },
      R3: ['guardrail/text-jsx'],
    },
  },
  'ADR-0014': {
    scope: {
      paths: ['apps/mobile/src/_app/routes/tabs-layout.tsx'],
    },
    rules: {
      R1: ['guardrail/nav-js-tabs'],
      R2: {
        convention:
          'La barre de navigation par onglets de apps/mobile/src/_app/routes/tabs-layout.tsx est composée avec NativeTabs de expo-router/unstable-native-tabs, le seul composant qui rend des onglets natifs par plateforme.',
      },
    },
  },
  'ADR-0015': {
    scope: {
      paths: ['apps/mobile/src/shared/lib/storage/**', 'apps/mobile/src/_app/model/**'],
    },
    rules: {
      R1: ['guardrail/module-react-native-mmkv'],
      R2: {
        convention:
          'Le buster du cache de PersistQueryClientProvider est CACHE_BUSTER, la constante que pnpm gen calcule en hachant les sources de packages/contracts ; gen:check refuse une valeur périmée, donc un changement des contrats jette le cache persisté.',
      },
    },
  },
  'ADR-0016': {
    scope: {
      paths: [
        'apps/mobile/jest.config.cjs',
        'apps/mobile/jest.setup.ts',
        'apps/mobile/**/*.test.ts',
        'apps/mobile/**/*.test.tsx',
      ],
    },
    rules: {
      R1: ['guardrail/test-describe-only', 'guardrail/test-it-only', 'guardrail/test-test-only'],
      R2: {
        convention:
          'Les composants et la logique de apps/mobile sont testés par jest-expo et RNTL, configurés par apps/mobile/jest.config.cjs ; Vitest teste les paquets et les outils, Maestro teste les parcours.',
      },
      R3: {
        convention:
          'Les tests de apps/mobile passent par la commande test:app de pnpm verify, déclarée dans tools/governance/src/commands.ts ; le pre-commit rejoue la vérification, donc chaque commit les passe.',
      },
    },
  },
  'ADR-0017': {
    scope: {
      paths: [
        'apps/mobile/src/_app/model/fonts.ts',
        'apps/mobile/src/_app/routes/startup-gate.tsx',
        'apps/mobile/src/shared/lib/startup/**',
      ],
    },
    rules: {
      R1: ['guardrail/module-expo-font', 'guardrail/module-expo-splash-screen'],
      R2: {
        convention:
          'Une famille de police est un token FontFamily de @huma/design-tokens (FONT_FAMILIES), nommée par jeu de faces et résolue pour un variant par typographyAt, seule porte de la table ; la primitive Text prend un nom de variant, jamais une chaîne, donc aucune police libre n’entre dans le rendu.',
      },
    },
  },
  'ADR-0018': {
    scope: {
      paths: ['apps/mobile/src/shared/ui/primitives/image/**', 'apps/mobile/src/shared/ui/primitives/icon/**'],
    },
    rules: {
      R1: ['guardrail/module-expo-image', 'guardrail/module-expo-symbols'],
      R2: ['guardrail/icon-symbol'],
    },
  },
  'ADR-0020': {
    scope: {
      paths: ['packages/mock-content/**', 'packages/mock-api/**', 'packages/design-tokens/src/sections.ts'],
    },
    rules: {
      R1: {
        convention:
          'Aucun média n’entre dans packages/mock-content : le dépôt ne suit que les visuels que son propre générateur écrit, et le manifeste des images est produit par pnpm --filter @huma/mock-content generate, jamais par un téléchargement.',
      },
      R2: {
        convention:
          'IMAGE_KEY impose la forme « identifiant d’item, puis sujet » ; validateCorpus refuse une clé qui nomme un autre item ou qui sert deux images, et le test des visuels exige un fichier par clé et par largeur, sans orphelin.',
      },
      R3: {
        convention:
          'artworkSvg ne lit que la clé et la couleur de la rubrique : la graine du dessin est un hachage de la clé, si bien qu’une regénération redonne les mêmes octets, ce qu’un test tient.',
      },
    },
  },
  'ADR-0021': {
    scope: {
      paths: ['apps/mobile/src/shared/api/**', 'apps/mobile/src/entities/**', 'packages/eslint-config/src/query.ts'],
    },
    rules: {
      R1: ['guardrail/module-huma-mock-api', 'guardrail/module-huma-mock-content'],
      R2: ['guardrail/query-options', 'guardrail/query-options-exempt'],
    },
  },
  'ADR-0022': {
    scope: {
      paths: ['apps/mobile/src/shared/ui/primitives/list/**', 'apps/mobile/src/shared/ui/primitives/scroll/**'],
    },
    rules: {
      R1: ['guardrail/module-shopify-flash-list'],
      R2: {
        convention:
          'La primitive List rend la seule région défilante verticale de son écran et porte elle-même les bandes qui suivent le défilement : elle crée la valeur partagée du décalage, qu’aucune autre place ne peut nommer puisque react-native-reanimated est confinée aux primitives. L’autre région défilante de l’app, la primitive Scroll, exige son axe : aucun appel ne peut prendre l’axe vertical sans l’écrire, et une bande qui défile en travers ne dispute aucun geste à la liste.',
      },
    },
  },
  'ADR-0023': {
    scope: {
      paths: ['apps/mobile/src/shared/lib/routing/**'],
    },
    rules: {
      R1: ['guardrail/module-expo-router'],
      R2: ['guardrail/route-params', 'guardrail/route-params-exempt'],
      R4: ['guardrail/module-expo-linking'],
      R3: {
        convention:
          'Un identifiant du domaine est une chaîne marquée que seul l’analyseur des contrats produit : un écran qui en déclare un ne peut pas l’obtenir d’un paramètre brut, et la marque est inimitable puisque l’assertion de type est interdite partout.',
      },
    },
  },
  'ADR-0024': {
    scope: {
      paths: ['apps/mobile/src/features/**', 'apps/mobile/src/shared/lib/storage/**'],
    },
    rules: {
      R1: ['guardrail/module-zustand'],
      R2: {
        convention:
          'La façade du stockage n’accepte qu’une clé du registre : son paramètre est typé sur les valeurs de la table, si bien qu’une clé écrite à la main ne compile pas, et le registre reste le seul endroit où lire ce que l’app pose sur le disque.',
      },
      R3: {
        convention:
          'Chaque magasin nomme la version du format qu’il écrit et le middleware de persistance l’inscrit dans l’enveloppe posée sur le disque ; elle est relue à la restauration, et un format d’une autre version passe par la migration ou est écarté. Un test par magasin relit l’enveloppe écrite et y vérifie la version, le middleware laissant par défaut une version nulle à qui ne la nomme pas.',
      },
      R4: {
        convention:
          'Ce qui revient du disque est une chaîne quelconque, qu’un fichier modifié à la main peut avoir remplacée : chaque magasin la relit valeur par valeur avant de rien servir — par l’analyseur marqué des contrats quand la valeur est un identifiant, contre la liste close des valeurs admises quand c’est un réglage — et ce qui n’en ressort pas est laissé pour la valeur du journal, si bien qu’un disque modifié ne peut pas placer dans un magasin une valeur que le reste de l’app croirait validée.',
      },
    },
  },
} as const satisfies Bindings<ProofId>;
