import type { Bindings } from '@huma/adr/bindings';
import { repoPath } from '@huma/kit/paths';
import type { ProofId } from './proofs.ts';

/** Where the bindings live, as the index and the diagnostics name them. */
export const BINDINGS_PATH = repoPath('tools/governance/src/bindings.ts');

/**
 * How each binding rule of each ADR is proven, and what each ADR governs. ADR files are frozen once decided; this file
 * follows the code instead, and `adr:check` keeps it in step with the rules written in the ADRs.
 */
export const BINDINGS = {
  'ADR-0000': {
    scope: {
      paths: [
        'docs/adr/**',
        'tools/adr/**',
        'tools/agents/src/guard.ts',
        'tools/governance/src/acknowledgments.ts',
        'tools/governance/src/bindings.ts',
        'tools/governance/src/bindings-file.ts',
        'tools/governance/src/cli/adr-check.ts',
        'tools/governance/src/cli/adr-decide.ts',
        'tools/governance/src/cli/adr-new.ts',
        'tools/governance/src/cli/adr-status.ts',
        'tools/governance/src/commit-refs.ts',
        'tools/governance/src/decision.ts',
        'tools/governance/src/proofs/commit-refs.ts',
        'tools/governance/src/workspace.ts',
      ],
    },
    rules: {
      R1: [
        'adr/valid',
        'adr/valid-words-limit',
        'adr/valid-nbsp',
        'adr/valid-link-target',
        'adr/valid-root-link-target',
        'adr/encoding-invalid-utf8',
        'adr/encoding-bom',
        'adr/encoding-not-nfc',
        'adr/encoding-invisible',
        'adr/encoding-invisible-crlf',
        'adr/frontmatter-missing',
        'adr/frontmatter-yaml',
        'adr/frontmatter-schema',
        'adr/frontmatter-not-canonical',
        'adr/frontmatter-not-canonical-delimiter',
        'adr/markdown-node',
        'adr/markdown-heading-depth',
        'adr/markdown-task-list',
        'adr/markdown-link-title',
        'adr/markdown-indented-code',
        'adr/markdown-code-language',
        'adr/title-missing',
        'adr/title-not-first',
        'adr/title-duplicate',
        'adr/title-rich',
        'adr/title-no-letter',
        'adr/title-too-long',
        'adr/title-forbidden-character',
        'adr/title-final-punctuation',
        'adr/slug-mismatch',
        'adr/section-content-before',
        'adr/section-order',
        'adr/section-subsection',
        'adr/section-consequences',
        'adr/section-pros-and-cons-text',
        'adr/words-limit',
        'adr/link-scheme',
        'adr/link-malformed',
        'adr/link-empty',
        'adr/link-scheme-protocol-relative',
        'adr/link-target-missing',
        'adr/mention-malformed',
        'adr/mention-unknown',
        'adr/path-directory',
        'adr/path-name',
        'new/title-refused',
      ],
      R2: ['adr/frontmatter-format-unknown', 'adr/frontmatter-format-outdated', 'adr/format-regression'],
      R3: [
        'adr/context-question-missing',
        'adr/context-question-shape',
        'adr/valid-question-code',
        'adr/context-facts-missing',
        'adr/context-fact-shape',
        'adr/context-fact-unsourced',
        'adr/context-fact-fragment-only',
        'adr/context-stray-block',
        'adr/criteria-list',
        'adr/criteria-label',
        'adr/options-list',
        'adr/options-name',
        'adr/options-duplicate',
        'adr/options-too-few',
        'adr/options-subsections',
        'adr/decision-chosen-shape',
        'adr/decision-chosen-unknown',
        'adr/decision-chosen-duplicate',
        'adr/decision-rules-missing',
        'adr/decision-rule-label',
        'adr/decision-trailing-block',
        'adr/decision-no-binding-rule',
        'adr/argument-list',
        'adr/argument-shape',
        'adr/consequences-balance',
        'adr/option-chosen-without-good',
        'adr/option-rejected-without-bad',
        'adr/citation-malformed',
        'adr/citation-unknown',
        'adr/citation-chosen-missing',
        'adr/citation-argument-missing',
        'adr/citation-criterion-unused',
        'adr/reevaluation-list',
        'adr/reevaluation-count',
      ],
      R4: [
        'adr/keyword-forbidden',
        'adr/keyword-forbidden-unaccented',
        'adr/keyword-negation',
        'adr/keyword-negation-may',
        'adr/keyword-negation-without-ne',
        'adr/keyword-forbidden-hyphenated',
        'adr/keyword-count',
        'adr/keyword-outside-rule',
      ],
      R5: [
        'adr/number-duplicate',
        'adr/deleted',
        'adr/number-reused',
        'adr/valid-restored',
        'adr/number-duplicate-keeps-lineage',
        'new/parallel-worktrees',
        'new/unreserved-race',
        'new/reserved-number-skipped',
        'new/parallel-creations',
        'new/abandoned-number-kept',
      ],
      R6: [
        'adr/transition-first-not-proposed',
        'adr/transition-forbidden',
        'adr/transition-uncommitted',
        'decide/failing-checks-refused',
        'decide/unknown-adr-refused',
        'decide/stale-artifacts-refused',
        'decide/concurrent-change-refused',
        'decide/failing-result-undone',
        'decide/dirty-tree-refused',
        'decide/already-decided-refused',
        'adr/valid-merge-acceptance',
        'adr/decision-content-changed',
        'adr/decision-content-changed-staged',
        'decide/rejects',
        'decide/valid-message-accepted',
        'decide/valid-message-superseding',
      ],
      R7: [
        'adr/frozen-modified',
        'adr/frozen-after-unreadable',
        'adr/frozen-renamed',
        'adr/history-shallow',
        'adr/history-not-repository',
        'adr/valid-accepted',
        'adr/valid-code-block-status',
        'guard/decided-write',
        'format/prettier-keeps-fingerprint',
        'format/embedded-code-changes-fingerprint',
      ],
      R8: [
        'agent/decide-script',
        'agent/decide-run-script',
        'agent/decide-entry',
        'agent/decide-masked-session',
        'agent/decide-in-subshell',
        'agent/decide-in-substitution',
        'agent/decide-monitor',
        'agent/decide-relative-entry',
        'agent/decide-exec-runner',
        'agent/decide-eval-code',
        'agent/decide-mentioned',
        'agent/decide-source-read',
        'agent/adr-check',
        'agent/unset-session',
        'agent/empty-session',
        'agent/unexport-session',
        'agent/ignore-environment',
        'agent/status-edit',
        'agent/decided-edit',
        'agent/decided-multi-edit',
        'agent/proposed-edit-missing-text',
        'agent/relative-status-write',
        'agent/shell-sed-status',
        'agent/shell-sed-proposed',
        'agent/shell-cd-relative',
        'agent/shell-loop-pattern',
        'agent/shell-heredoc-decided',
        'agent/shell-append-decided',
        'agent/shell-remove-decided',
        'agent/shell-remove-proposed',
        'agent/shell-rename-decided',
        'agent/shell-copy-decided',
        'agent/shell-remove-tree',
        'agent/shell-find-delete',
        'agent/shell-find-refactor',
        'agent/shell-symlink-decided',
        'agent/write-outside',
        'agent/write-settings',
        'agent/write-local-settings',
        'agent/write-through-symlink',
        'agent/shell-local-settings',
        'agent/shell-home-settings',
        'agent/shell-tee-settings',
        'agent/unreadable-input',
        'agent/input-without-tool',
        'agent/shell-without-command',
        'agent/write-without-path',
        'agent/code-sensitive',
        'agent/code-innocuous',
        'agent/other-tool',
        'agent/valid-no-local-settings',
        'agent/valid-local-permissions',
        'agent/local-settings-hooks-disabled',
        'agent/local-settings-unreadable',
        'guard/status-change',
        'guard/new-decided-file',
        'guard/new-skeleton',
        'guard/tagged-status',
        'guard/escaped-status',
        'guard/non-canonical-proposed',
        'guard/escaped-decided-rewrite',
        'guard/unknown-result',
        'decide/agent-refused',
        'adr/decision-by-agent',
        'adr/decision-by-agent-worktree',
        'adr/valid-agent-merges-human-decision',
        'claude-hook/settings-command-denies',
        'claude-hook/settings-command-allows',
        'claude-hook/failure-denies-sensitive',
        'claude-hook/failure-allows-innocuous',
      ],
      R9: [
        'adr/binding-malformed-id',
        'adr/binding-unknown-adr',
        'adr/binding-inactive',
        'adr/binding-missing',
        'adr/binding-rule-unbound',
        'adr/binding-rule-extra',
        'adr/valid-optional-binding',
        'adr/binding-optional-only',
        'adr/binding-convention-empty',
        'adr/binding-proof-unknown',
        'adr/binding-no-proven-rule',
        'adr/scope-glob-invalid',
        'adr/scope-glob-duplicate',
        'adr/scope-glob-empty',
        'adr/accept-proof-failing',
        'adr/valid-staged-acceptance',
        'decide/failing-proof-refused',
        'decide/unbound-acceptance-refused',
        'decide/accepts',
      ],
      R10: ['gen/stale-index', 'gen/missing-index', 'gen/in-step'],
      R11: [
        'adr/supersedes-unknown',
        'adr/supersedes-newer',
        'adr/supersedes-not-accepted',
        'adr/supersedes-several',
        'adr/valid-superseded',
        'adr/decision-supersedes-added',
        'decide/accepts-superseding',
      ],
      R12: [
        'adr/valid-acknowledged',
        'adr/acknowledgment-unused',
        'adr/valid-frozen-acknowledged',
        'adr/frozen-acknowledged-then-edited',
      ],
      R13: [
        'adr/valid-history',
        'adr/valid-renamed-proposed',
        'guard/proposed-edit',
        'agent/proposed-edit',
        'agent/proposed-edit-straight-quotes',
        'agent/shell-heredoc-proposed',
        'agent/shell-rename-proposed',
        'agent/shell-copy-proposed',
      ],
    },
  },
  'ADR-0001': {
    scope: {
      paths: [
        'pnpm-workspace.yaml',
        'pnpm-lock.yaml',
        'package.json',
        'apps/*/package.json',
        'packages/*/package.json',
        'tools/*/package.json',
        'tools/deps/**',
        'tools/governance/src/cli/deps-check.ts',
      ],
    },
    rules: {
      R1: [
        'deps/catalog-missing',
        'deps/catalog-stale',
        'deps/catalog-unused',
        'deps/single-version',
        'deps/lockfile-version',
      ],
      R2: [
        'deps/catalog-range',
        'deps/sibling-version',
        'deps/single-instance',
        'deps/importer-stale',
        'deps/importer-missing',
        'deps/importer-extra',
        'deps/importer-unknown',
        'deps/private-copy',
        'deps/private-copy-allowed',
        'deps/private-copy-unused',
      ],
      R3: ['deps/tested-version', 'deps/untested-version'],
      R4: ['deps/specifier-form'],
    },
  },
  'ADR-0002': {
    scope: {
      paths: [
        'apps/mobile/app.config.ts',
        'apps/mobile/app/**',
        'tools/expo/**',
        'tools/governance/src/cli/expo-types.ts',
      ],
    },
    rules: {
      R1: ['deps/tested-version', 'deps/untested-version'],
      R2: [
        'expo/routes-directory',
        'expo/tsconfig-rewrite',
        'expo/gitignore-rewrite',
        'expo/routes-invalid',
        'expo/typed-routes',
      ],
      R3: {
        convention:
          'Les invariants d’app.config sont vérifiés par tools/expo/src/app-config.test.ts, hors du banc de fixtures.',
      },
    },
  },
  'ADR-0003': {
    scope: {
      paths: [
        'packages/tsconfig/**',
        'tsconfig.json',
        'apps/*/tsconfig.json',
        'packages/*/tsconfig.json',
        'tools/*/tsconfig.json',
        'tools/governance/src/tsconfig-snapshot.ts',
      ],
    },
    rules: {
      R1: ['deps/single-instance', 'deps/single-version'],
      R2: {
        convention:
          'Les options strictes de chaque projet sont vérifiées par tools/governance/src/tsconfig-snapshot.test.ts contre le préréglage packages/tsconfig/strict.json.',
      },
      R3: ['guardrail/node-import-js', 'guardrail/node-export-js', 'guardrail/node-dynamic-import-js'],
      R4: ['guardrail/node-decorator', 'guardrail/node-accessor'],
      R5: ['deps/reference-missing', 'deps/reference-undeclared'],
    },
  },
  'ADR-0004': {
    scope: {
      paths: [
        'packages/eslint-config/**',
        'tools/lint/**',
        'tools/governance/src/cli/lint.ts',
        'tools/governance/src/cli/format.ts',
        'tools/guardrails/src/effective-config.test.ts',
      ],
    },
    rules: {
      R1: ['lint/rule', 'lint/unconfigured', 'lint/parse-error', 'lint/git-ignored', 'lint/clean'],
      R2: ['lint/inline-config', 'lint/suppressed', 'lint/suppressions-file'],
      R3: ['lint/unformatted', 'lint/format-error', 'lint/prettier-ignored'],
      R4: {
        convention:
          'L’absence d’avertissement et le maintien à error des bans typés nommés sont vérifiés par tools/guardrails/src/effective-config.test.ts.',
      },
      R5: ['lint/deprecated-rule'],
    },
  },
  'ADR-0005': {
    scope: {
      paths: [
        'apps/mobile/app/**',
        'apps/mobile/src/**',
        'packages/architecture/**',
        'tools/structure/**',
        'tools/governance/src/cli/structure-check.ts',
      ],
    },
    rules: {
      R1: [
        'structure/ambiguous-slice-names',
        'structure/inconsistent-naming',
        'structure/insignificant-slice',
        'structure/no-reserved-folder-names',
        'structure/repetitive-naming',
        'structure/excessive-slicing',
        'structure/shared-lib-grouping',
        'structure/import-locality',
        'structure/clean',
      ],
      R2: ['guardrail/place-unknown-file', 'guardrail/unknown-file-imports'],
      R3: ['guardrail/entry-re-export', 'guardrail/export-all'],
      R4: ['structure/cycle', 'structure/cycle-in-routes'],
      R5: ['guardrail/route-re-export', 'guardrail/route-error-boundary'],
    },
  },
  'ADR-0006': {
    scope: {
      paths: ['packages/architecture/**', 'packages/eslint-config/src/index.ts'],
    },
    rules: {
      R1: [
        'guardrail/import-primitive',
        'guardrail/import-component',
        'guardrail/import-entity',
        'guardrail/import-feature',
        'guardrail/import-page',
        'guardrail/import-app',
        'guardrail/import-route',
        'guardrail/import-api',
        'guardrail/import-config',
        'guardrail/import-i18n',
        'guardrail/import-lib',
      ],
      R2: ['guardrail/import-page-internals'],
      R3: [
        'guardrail/module-react-native',
        'guardrail/module-react-native-entry',
        'guardrail/module-react-native-platform',
        'guardrail/module-react-native-namespace',
        'guardrail/module-react-native-gesture-handler',
        'guardrail/module-react-native-reanimated',
      ],
      R4: ['guardrail/platform-variant', 'guardrail/platform-variant-primitive'],
    },
  },
  'ADR-0007': {
    scope: {
      paths: [
        'packages/architecture/src/glossary.ts',
        'packages/eslint-config/src/spelling.ts',
        'packages/eslint-config/cspell.json',
      ],
    },
    rules: {
      R1: ['guardrail/spelling-unknown'],
      R2: [
        'guardrail/glossary-term',
        'guardrail/glossary-synonym',
        'lint/glossary-word-inside',
        'lint/glossary-file-name',
      ],
      R3: [
        'guardrail/naming-file',
        'guardrail/naming-folder',
        'guardrail/naming-route-conventions',
        'guardrail/naming-route-file',
        'guardrail/naming-route-folder',
      ],
    },
  },
  'ADR-0008': {
    scope: {
      paths: [
        'tools/git-hooks/**',
        'tools/fixtures/**',
        'tools/governance/src/cli/git-hook.ts',
        'tools/governance/src/cli/hooks-check.ts',
        'tools/governance/src/cli/hooks-install.ts',
      ],
    },
    rules: {
      R1: [
        'git/header',
        'git/header-length',
        'git/type',
        'git/scope',
        'git/scope-before-package',
        'git/body-separator',
        'git/not-canonical',
        'git/generated-fixup',
        'git/control-character',
        'git/valid-message',
      ],
      R2: [
        'git/refs-missing',
        'git/refs-missing-commit-msg',
        'git/refs-format',
        'git/refs-order',
        'git/refs-extra',
        'git/refs-in-prose',
        'git/refs-unrelated-cited',
        'git/refs-scope-required',
        'git/refs-adr-file-required',
        'git/trailer-unknown',
      ],
      R3: [
        'git/hook-missing',
        'git/hook-modified',
        'git/hook-not-executable',
        'git/hook-unexpected',
        'git/hooks-directory-link',
        'git/hooks-path',
        'git/hooks-path-worktree',
        'git/install-refused-hooks-path',
        'git/config-include',
        'git/no-verify-through-shims',
        'git/valid-installation',
        'git/valid-commit-through-shims',
      ],
      R4: [
        'git/verify-failed',
        'git/verify-skipped',
        'git/verify-skipped-index-changed',
        'git/verify-skipped-marker-forged',
        'git/verify-skipped-marker-reused',
        'git/tree-changed',
        'git/index-flagged',
        'git/unstaged',
        'git/unstaged-before-checks',
        'git/untracked',
        'git/unmerged',
        'git/valid-pre-commit',
        'git/valid-staging',
        'git/valid-verified-tree',
      ],
      R5: {
        convention:
          'Le banc de fixtures de tools/fixtures et les tests de couverture et de mutation de chaque liste de preuves prouvent que chaque garde-fou se déclenche exactement sur ses codes.',
      },
      R6: [
        'git/history-bypassed-commit',
        'git/history-replaced-commit',
        'git/patch-refused',
        'git/anchor-not-ancestor',
        'git/anchor-unknown',
      ],
    },
  },
} as const satisfies Bindings<ProofId>;
