import type { Bindings } from '@huma/adr/bindings';
import { CLAUDE_SETTINGS_PATH } from '@huma/agents/policy';
import { repoPath } from '@huma/kit/paths';
import type { ProofId } from './proofs.ts';

/** Where the bindings live, as the index and the diagnostics name them. */
export const BINDINGS_PATH = repoPath('tools/governance/src/bindings.ts');

/**
 * How each binding rule of each ADR is proven, and what each ADR governs. ADR files are frozen once decided; this file
 * follows the code instead, and `adr:check` keeps it in step with the rules written in the ADRs.
 */
export const BINDINGS = {
  'ADR-0000': {
    scope: {
      paths: [
        'docs/adr/**',
        'tools/adr/**',
        'tools/agents/**',
        'tools/fixtures/**',
        'tools/governance/**',
        'tools/kit/**',
        CLAUDE_SETTINGS_PATH,
      ],
    },
    rules: {
      R1: [
        'adr/valid',
        'adr/valid-words-limit',
        'adr/valid-nbsp',
        'adr/valid-link-target',
        'adr/valid-root-link-target',
        'adr/encoding-invalid-utf8',
        'adr/encoding-bom',
        'adr/encoding-not-nfc',
        'adr/encoding-invisible',
        'adr/encoding-invisible-crlf',
        'adr/frontmatter-missing',
        'adr/frontmatter-yaml',
        'adr/frontmatter-schema',
        'adr/frontmatter-not-canonical',
        'adr/frontmatter-not-canonical-delimiter',
        'adr/markdown-node',
        'adr/markdown-heading-depth',
        'adr/markdown-task-list',
        'adr/markdown-link-title',
        'adr/markdown-indented-code',
        'adr/markdown-code-language',
        'adr/title-missing',
        'adr/title-not-first',
        'adr/title-duplicate',
        'adr/title-rich',
        'adr/title-no-letter',
        'adr/title-too-long',
        'adr/title-forbidden-character',
        'adr/title-final-punctuation',
        'adr/slug-mismatch',
        'adr/section-content-before',
        'adr/section-order',
        'adr/section-subsection',
        'adr/section-consequences',
        'adr/section-pros-and-cons-text',
        'adr/words-limit',
        'adr/link-scheme',
        'adr/link-malformed',
        'adr/link-empty',
        'adr/link-scheme-protocol-relative',
        'adr/link-target-missing',
        'adr/mention-malformed',
        'adr/mention-unknown',
        'adr/path-directory',
        'adr/path-name',
        'new/title-refused',
      ],
      R2: ['adr/frontmatter-format-unknown', 'adr/frontmatter-format-outdated', 'adr/format-regression'],
      R3: [
        'adr/context-question-missing',
        'adr/context-question-shape',
        'adr/valid-question-code',
        'adr/context-facts-missing',
        'adr/context-fact-shape',
        'adr/context-fact-unsourced',
        'adr/context-fact-fragment-only',
        'adr/context-stray-block',
        'adr/criteria-list',
        'adr/criteria-label',
        'adr/options-list',
        'adr/options-name',
        'adr/options-duplicate',
        'adr/options-too-few',
        'adr/options-subsections',
        'adr/decision-chosen-shape',
        'adr/decision-chosen-unknown',
        'adr/decision-chosen-duplicate',
        'adr/decision-rules-missing',
        'adr/decision-rule-label',
        'adr/decision-trailing-block',
        'adr/decision-no-binding-rule',
        'adr/argument-list',
        'adr/argument-shape',
        'adr/consequences-balance',
        'adr/option-chosen-without-good',
        'adr/option-rejected-without-bad',
        'adr/citation-malformed',
        'adr/citation-unknown',
        'adr/citation-chosen-missing',
        'adr/citation-argument-missing',
        'adr/citation-criterion-unused',
        'adr/reevaluation-list',
        'adr/reevaluation-count',
      ],
      R4: [
        'adr/keyword-forbidden',
        'adr/keyword-forbidden-unaccented',
        'adr/keyword-negation',
        'adr/keyword-negation-may',
        'adr/keyword-negation-without-ne',
        'adr/keyword-forbidden-hyphenated',
        'adr/keyword-count',
        'adr/keyword-outside-rule',
      ],
      R5: [
        'adr/number-duplicate',
        'adr/deleted',
        'adr/number-reused',
        'adr/valid-restored',
        'adr/number-duplicate-keeps-lineage',
        'new/parallel-worktrees',
        'new/unreserved-race',
        'new/reserved-number-skipped',
        'new/parallel-creations',
        'new/abandoned-number-kept',
      ],
      R6: [
        'adr/transition-first-not-proposed',
        'adr/transition-forbidden',
        'adr/transition-uncommitted',
        'decide/failing-checks-refused',
        'decide/unknown-adr-refused',
        'decide/stale-artifacts-refused',
        'decide/concurrent-change-refused',
        'decide/failing-result-undone',
        'decide/dirty-tree-refused',
        'decide/already-decided-refused',
        'adr/valid-merge-acceptance',
        'adr/decision-content-changed',
        'adr/decision-content-changed-staged',
        'decide/valid-message-accepted',
        'decide/valid-message-superseding',
      ],
      R7: [
        'adr/frozen-modified',
        'adr/frozen-after-unreadable',
        'adr/frozen-renamed',
        'adr/history-shallow',
        'adr/history-not-repository',
        'adr/valid-accepted',
        'adr/valid-code-block-status',
        'guard/decided-write',
        'format/prettier-keeps-fingerprint',
        'format/embedded-code-changes-fingerprint',
      ],
      R8: [
        'agent/decide-script',
        'agent/decide-run-script',
        'agent/decide-entry',
        'agent/decide-masked-session',
        'agent/decide-in-subshell',
        'agent/decide-in-substitution',
        'agent/decide-monitor',
        'agent/decide-relative-entry',
        'agent/decide-exec-runner',
        'agent/decide-eval-code',
        'agent/decide-mentioned',
        'agent/decide-source-read',
        'agent/adr-check',
        'agent/unset-session',
        'agent/empty-session',
        'agent/unexport-session',
        'agent/ignore-environment',
        'agent/status-edit',
        'agent/decided-edit',
        'agent/decided-multi-edit',
        'agent/proposed-edit-missing-text',
        'agent/relative-status-write',
        'agent/shell-sed-status',
        'agent/shell-sed-proposed',
        'agent/shell-cd-relative',
        'agent/shell-loop-pattern',
        'agent/shell-heredoc-decided',
        'agent/shell-append-decided',
        'agent/shell-remove-decided',
        'agent/shell-remove-proposed',
        'agent/shell-rename-decided',
        'agent/shell-copy-decided',
        'agent/shell-remove-tree',
        'agent/shell-find-delete',
        'agent/shell-find-refactor',
        'agent/shell-symlink-decided',
        'agent/write-outside',
        'agent/write-settings',
        'agent/write-local-settings',
        'agent/write-through-symlink',
        'agent/shell-local-settings',
        'agent/shell-home-settings',
        'agent/shell-tee-settings',
        'agent/unreadable-input',
        'agent/shell-without-command',
        'agent/code-sensitive',
        'agent/code-innocuous',
        'agent/other-tool',
        'agent/valid-no-local-settings',
        'agent/valid-local-permissions',
        'agent/local-settings-hooks-disabled',
        'agent/local-settings-unreadable',
        'guard/status-change',
        'guard/new-decided-file',
        'guard/new-skeleton',
        'guard/tagged-status',
        'guard/escaped-status',
        'guard/non-canonical-proposed',
        'guard/escaped-decided-rewrite',
        'guard/unknown-result',
        'decide/agent-refused',
        'adr/decision-by-agent',
        'adr/decision-by-agent-worktree',
        'adr/valid-agent-merges-human-decision',
        'claude-hook/settings-command-denies',
        'claude-hook/settings-command-allows',
        'claude-hook/failure-denies-sensitive',
        'claude-hook/failure-allows-innocuous',
      ],
      R9: [
        'adr/binding-malformed-id',
        'adr/binding-unknown-adr',
        'adr/binding-inactive',
        'adr/binding-missing',
        'adr/binding-rule-unbound',
        'adr/binding-rule-extra',
        'adr/valid-optional-binding',
        'adr/binding-optional-only',
        'adr/binding-convention-empty',
        'adr/binding-proof-unknown',
        'adr/binding-no-proven-rule',
        'adr/scope-glob-invalid',
        'adr/scope-glob-duplicate',
        'adr/scope-glob-empty',
        'adr/accept-proof-failing',
        'adr/valid-staged-acceptance',
        'decide/failing-proof-refused',
        'decide/unbound-acceptance-refused',
        'decide/accepts',
      ],
      R10: ['gen/stale-index', 'gen/missing-index', 'gen/in-step'],
      R11: [
        'adr/supersedes-unknown',
        'adr/supersedes-newer',
        'adr/supersedes-not-accepted',
        'adr/supersedes-several',
        'adr/valid-superseded',
        'adr/decision-supersedes-added',
        'decide/accepts-superseding',
      ],
      R12: [
        'adr/valid-acknowledged',
        'adr/acknowledgment-unused',
        'adr/valid-frozen-acknowledged',
        'adr/frozen-acknowledged-then-edited',
      ],
      R13: [
        'adr/valid-history',
        'adr/valid-renamed-proposed',
        'guard/proposed-edit',
        'agent/proposed-edit',
        'agent/proposed-edit-straight-quotes',
        'agent/shell-heredoc-proposed',
        'agent/shell-rename-proposed',
        'agent/shell-copy-proposed',
        'decide/rejects',
      ],
    },
  },
} as const satisfies Bindings<ProofId>;
