import type { DependencyPolicy } from '@huma/deps/check';
import type { WorkspaceFile } from '@huma/deps/workspace';
import { repoPath } from '@huma/kit/paths';

/** Directories whose subdirectories are the packages of the workspace; each such directory name is a commit scope. */
export const WORKSPACE_ROOTS = ['apps', 'packages', 'tools'] as const;

type WorkspaceRoot = (typeof WORKSPACE_ROOTS)[number];

/** The roots whose packages the packages of each root may depend on: tools serve the workspace, nothing ships them. */
const ROOT_DEPENDENCIES: Readonly<Record<WorkspaceRoot, readonly WorkspaceRoot[]>> = {
  apps: ['packages'],
  packages: ['packages'],
  tools: ['packages', 'tools'],
};

/**
 * `pnpm-workspace.yaml`, generated by `pnpm gen`. A version changes here first: the catalog pins exact versions, each
 * published more than a day before it enters, as `minimumReleaseAge` requires; `pnpm install` then follows.
 */
export const WORKSPACE_FILE: WorkspaceFile = {
  packages: WORKSPACE_ROOTS.map((root) => `${root}/*`),
  settings: {
    nodeLinker: 'isolated',
    enableGlobalVirtualStore: false,
    strictDepBuilds: true,
    // The resolver ships prebuilt bindings as optional dependencies: its postinstall would only rebuild them.
    allowBuilds: { 'unrs-resolver': false },
    strictPeerDependencies: true,
    // Every required peer but react-dom already resolves to a package the graph holds, so pnpm has only react-dom to
    // add. Left to add it, pnpm took react-dom 19.3.0 for Expo Router's web components whenever it resolved the app
    // again, and the install failed on the React 19.3 it asks for: twice on 25/09/2026. The graph is otherwise the
    // same without it, package for package.
    autoInstallPeers: false,
    pmOnFail: 'error',
    verifyDepsBeforeRun: 'error',
    minimumReleaseAge: 1440,
    catalogMode: 'strict',
    peerDependencyRules: {
      // The app runs on iOS and Android only: the web components Expo Router ships ask for react-dom, never loaded.
      ignoreMissing: ['react-dom'],
    },
    patchedDependencies: {
      // Explicit streaming buffer: quick first sound and one continuous native timeline (ADR-0044).
      'expo-audio@57.0.5': 'patches/expo-audio@57.0.5.patch',
      // The fix of 2.2.1 (Shopify/flash-list#2069), on the version the SDK tests. With no header pinned — a list
      // pulled or bounced past its top — the pinned header's interpolation has an empty input range, which the native
      // driver on iOS divides by: on the iPhone simulator on 25/09/2026, the wire went blank and stayed so, its rows
      // still answering touches. The SDK 58 preview still tests 2.0.2.
      '@shopify/flash-list@2.0.2': 'patches/@shopify__flash-list@2.0.2.patch',
      // Ours, not upstream's, which is unchanged in 4.28, and two things. A marked list laid in a pager registers
      // with the tab bar when its page comes to rest on the screen, and any marked list when the reader starts
      // dragging it. Upstream registers every marker as it reaches the window, so the front page's bar followed the
      // section beside the one on the screen, and never shrank under it.
      // And a field on a screen the reader was taken to is offered to their password manager. Attaching a screen's
      // fragment tells every view under it that it is no longer laid out, and Android holds back the autofill
      // notification for a focused view in that state until its next layout — which React Native never runs again,
      // the frame not having moved. So no request ever reached the manager: measured on a Nothing A065 (Android 16),
      // 0 sessions in 6 goes to the sign-in screen through the account, 6 in 6 with the patch, 0 in 6 again with it
      // taken out and the same build made again (26/09/2026). Upstream has it open as #4612, unfixed on main.
      'react-native-screens@4.26.2': 'patches/react-native-screens@4.26.2.patch',
    },
  },
  catalog: {
    '@babel/core': '7.29.7',
    '@babel/runtime': '7.29.7',
    '@cspell/eslint-plugin': '10.3.3',
    '@eslint/js': '10.0.1',
    '@expo-google-fonts/anton': '0.4.2',
    '@expo-google-fonts/atkinson-hyperlegible': '0.4.1',
    '@expo-google-fonts/overpass': '0.4.2',
    '@expo/dom-webview': '57.0.1',
    '@expo/log-box': '57.0.4',
    '@expo/metro-config': '57.0.12',
    '@expo/metro-runtime': '57.0.16',
    '@feature-sliced/steiger-plugin': '0.7.0',
    '@jest/globals': '29.7.0',
    '@react-native/jest-preset': '0.86.3',
    '@react-native/metro-config': '0.86.3',
    '@shopify/flash-list': '2.0.2',
    '@tanstack/eslint-plugin-query': '5.103.2',
    '@tanstack/react-query': '5.103.2',
    '@tanstack/react-query-persist-client': '5.103.2',
    '@testing-library/react-native': '14.0.1',
    '@types/mdast': '4.0.4',
    '@types/node': '24.13.6',
    '@types/react': '19.2.18',
    '@types/semver': '7.8.0',
    'babel-preset-expo': '57.0.13',
    'dependency-cruiser': '18.4.0',
    eslint: '10.11.0',
    'eslint-import-resolver-typescript': '4.4.5',
    'eslint-plugin-boundaries': '7.2.0',
    'eslint-plugin-check-file': '3.3.2',
    'eslint-plugin-react-hooks': '7.1.1',
    'eslint-plugin-react-x': '5.20.8',
    expo: '57.0.25',
    'expo-asset': '57.0.18',
    'expo-audio': '57.0.5',
    'expo-constants': '57.0.19',
    'expo-crypto': '57.0.3',
    'expo-dev-client': '57.0.19',
    'expo-font': '57.0.4',
    'expo-image': '57.0.5',
    'expo-linking': '57.0.11',
    'expo-router': '57.0.23',
    'expo-secure-store': '57.0.4',
    'expo-splash-screen': '57.0.9',
    'expo-symbols': '57.0.3',
    'expo-system-ui': '57.0.4',
    jest: '29.7.0',
    'jest-expo': '57.0.5',
    knip: '6.38.0',
    'mdast-util-from-markdown': '2.0.3',
    'mdast-util-frontmatter': '2.0.1',
    'mdast-util-gfm': '3.1.0',
    'micromark-extension-frontmatter': '2.0.0',
    'micromark-extension-gfm': '3.0.0',
    prettier: '3.9.9',
    react: '19.2.3',
    'react-native': '0.86.3',
    'react-native-gesture-handler': '2.32.0',
    'react-native-mmkv': '4.3.2',
    'react-native-nitro-modules': '0.37.1',
    'react-native-onesignal': '5.5.14',
    'react-native-reanimated': '4.5.1',
    'react-native-safe-area-context': '5.7.0',
    'react-native-screens': '4.26.2',
    'react-native-worklets': '0.10.1',
    'react-refresh': '0.14.2',
    semver: '7.8.5',
    sharp: '0.35.4',
    steiger: '0.6.0',
    'test-renderer': '1.2.0',
    thumbhash: '0.1.1',
    typescript: '6.0.3',
    'typescript-eslint': '8.70.1',
    vite: '8.3.0',
    vitest: '5.0.1',
    yaml: '2.9.1',
    zod: '4.6.5',
    zustand: '5.0.15',
  },
};

export const DEPENDENCY_POLICY: DependencyPolicy = {
  source: repoPath('tools/governance/src/workspace-manifest.ts'),
  roots: ROOT_DEPENDENCIES,
  // A second instance is a second copy in the bundle: React loses its hooks, native modules register twice.
  singleInstance: [
    'expo',
    'expo-modules-core',
    'expo-router',
    'react',
    'react-native',
    'react-native-mmkv',
    'react-native-nitro-modules',
    'react-native-onesignal',
    'react-native-reanimated',
    'react-native-safe-area-context',
    'react-native-screens',
    'react-native-worklets',
  ],
  singleVersion: {
    // Steiger resolves imports and reads tsconfig files with the TypeScript 5 it declares: its copy never checks types.
    typescript: ['@feature-sliced/filesystem', 'cosmiconfig', 'tsconfck'],
    // @expo/cli and Steiger validate their own inputs with zod 3: both run in Node beside the app, never inside it.
    zod: ['@expo/cli', 'steiger', 'zod-validation-error'],
  },
  confined: { packages: { zod: ['packages/contracts'] } },
};
