import type { DependencyPolicy } from '@huma/deps/check';
import type { WorkspaceFile } from '@huma/deps/workspace';
import { repoPath } from '@huma/kit/paths';

/** Directories whose subdirectories are the packages of the workspace; each package name is also a commit scope. */
export const WORKSPACE_ROOTS = ['apps', 'infra', 'packages', 'tools'] as const;

export type WorkspaceRoot = (typeof WORKSPACE_ROOTS)[number];

/** The roots whose packages the packages of each root may depend on: tools serve the workspace, nothing ships them. */
const ROOT_DEPENDENCIES: Readonly<Record<WorkspaceRoot, readonly WorkspaceRoot[]>> = {
  apps: ['packages'],
  infra: ['packages', 'tools'],
  packages: ['packages'],
  tools: ['packages', 'tools'],
};

/**
 * `pnpm-workspace.yaml`, generated by `pnpm gen`. A version changes here first: the catalog pins exact versions, each
 * published more than a day before it enters, as `minimumReleaseAge` requires; `pnpm install` then follows.
 */
export const WORKSPACE_FILE: WorkspaceFile = {
  packages: WORKSPACE_ROOTS.map((root) => `${root}/*`),
  settings: {
    nodeLinker: 'isolated',
    enableGlobalVirtualStore: false,
    strictDepBuilds: true,
    // The resolver ships prebuilt bindings as optional dependencies: its postinstall would only rebuild them.
    allowBuilds: { 'unrs-resolver': false },
    strictPeerDependencies: true,
    pmOnFail: 'error',
    verifyDepsBeforeRun: 'error',
    minimumReleaseAge: 1440,
    catalogMode: 'strict',
    peerDependencyRules: {
      // The app runs on iOS and Android only: the web components Expo Router ships ask for react-dom, never loaded.
      ignoreMissing: ['react-dom'],
    },
  },
  catalog: {
    '@babel/core': '7.29.7',
    '@cspell/eslint-plugin': '10.3.1',
    '@eslint/js': '10.0.1',
    '@expo/dom-webview': '57.0.1',
    '@expo/log-box': '57.0.4',
    '@expo/metro-config': '57.0.12',
    '@expo/metro-runtime': '57.0.15',
    '@feature-sliced/steiger-plugin': '0.7.0',
    '@react-native/metro-config': '0.86.3',
    '@types/mdast': '4.0.4',
    '@types/node': '24.13.4',
    '@types/react': '19.2.18',
    '@types/semver': '7.8.0',
    'babel-preset-expo': '57.0.11',
    'dependency-cruiser': '18.3.0',
    eslint: '10.10.0',
    'eslint-import-resolver-typescript': '4.4.5',
    'eslint-plugin-boundaries': '7.2.0',
    'eslint-plugin-check-file': '3.3.2',
    'eslint-plugin-react-hooks': '7.1.1',
    'eslint-plugin-react-x': '5.19.0',
    expo: '57.0.22',
    'expo-constants': '57.0.18',
    'expo-dev-client': '57.0.19',
    'expo-font': '57.0.4',
    'expo-linking': '57.0.10',
    'expo-router': '57.0.21',
    'mdast-util-from-markdown': '2.0.3',
    'mdast-util-frontmatter': '2.0.1',
    'mdast-util-gfm': '3.1.0',
    'micromark-extension-frontmatter': '2.0.0',
    'micromark-extension-gfm': '3.0.0',
    prettier: '3.9.6',
    react: '19.2.3',
    'react-native': '0.86.3',
    'react-native-gesture-handler': '2.32.0',
    'react-native-reanimated': '4.5.1',
    'react-native-safe-area-context': '5.7.0',
    'react-native-screens': '4.26.2',
    'react-native-worklets': '0.10.1',
    'react-refresh': '0.14.2',
    semver: '7.8.5',
    steiger: '0.6.0',
    typescript: '6.0.3',
    'typescript-eslint': '8.70.0',
    vite: '8.3.0',
    vitest: '5.0.0',
    yaml: '2.9.1',
    zod: '4.5.4',
  },
};

export const DEPENDENCY_POLICY: DependencyPolicy = {
  source: repoPath('tools/governance/src/workspace-manifest.ts'),
  roots: ROOT_DEPENDENCIES,
  // A second instance is a second copy in the bundle: React loses its hooks, native modules register twice.
  singleInstance: [
    'expo',
    'expo-modules-core',
    'expo-router',
    'react',
    'react-native',
    'react-native-reanimated',
    'react-native-safe-area-context',
    'react-native-screens',
    'react-native-worklets',
  ],
  singleVersion: {
    // Steiger resolves imports and reads tsconfig files with the TypeScript 5 it declares: its copy never checks types.
    typescript: ['@feature-sliced/filesystem', 'cosmiconfig', 'tsconfck'],
    // @expo/cli and Steiger validate their own inputs with zod 3: both run in Node beside the app, never inside it.
    zod: ['@expo/cli', 'steiger', 'zod-validation-error'],
  },
};
