import type { DependencyPolicy } from '@huma/deps/check';
import type { WorkspaceFile } from '@huma/deps/workspace';
import { repoPath } from '@huma/kit/paths';

/** Directories whose subdirectories are the packages of the workspace; each package name is also a commit scope. */
export const WORKSPACE_ROOTS = ['apps', 'infra', 'packages', 'tools'] as const;

export type WorkspaceRoot = (typeof WORKSPACE_ROOTS)[number];

/** The roots whose packages the packages of each root may depend on: tools serve the workspace, nothing ships them. */
const ROOT_DEPENDENCIES: Readonly<Record<WorkspaceRoot, readonly WorkspaceRoot[]>> = {
  apps: ['packages'],
  infra: ['packages', 'tools'],
  packages: ['packages'],
  tools: ['packages', 'tools'],
};

/**
 * `pnpm-workspace.yaml`, generated by `pnpm gen`. A version changes here first: the catalog pins exact versions, each
 * published more than a day before it enters, as `minimumReleaseAge` requires; `pnpm install` then follows.
 */
export const WORKSPACE_FILE: WorkspaceFile = {
  packages: WORKSPACE_ROOTS.map((root) => `${root}/*`),
  settings: {
    nodeLinker: 'isolated',
    enableGlobalVirtualStore: false,
    strictDepBuilds: true,
    strictPeerDependencies: true,
    pmOnFail: 'error',
    verifyDepsBeforeRun: 'error',
    minimumReleaseAge: 1440,
    catalogMode: 'strict',
    peerDependencyRules: { ignoreMissing: [] },
  },
  catalog: {
    '@eslint/js': '10.0.1',
    '@types/mdast': '4.0.4',
    '@types/node': '24.13.4',
    eslint: '10.10.0',
    'mdast-util-from-markdown': '2.0.3',
    'mdast-util-frontmatter': '2.0.1',
    'mdast-util-gfm': '3.1.0',
    'micromark-extension-frontmatter': '2.0.0',
    'micromark-extension-gfm': '3.0.0',
    prettier: '3.9.6',
    typescript: '6.0.3',
    'typescript-eslint': '8.70.0',
    vite: '8.3.0',
    vitest: '5.0.0',
    yaml: '2.9.1',
    zod: '4.5.4',
  },
};

export const DEPENDENCY_POLICY: DependencyPolicy = {
  source: repoPath('tools/governance/src/workspace-manifest.ts'),
  roots: ROOT_DEPENDENCIES,
  singleInstance: [],
  singleVersion: { typescript: [], zod: [] },
};
