# shellcheck shell=sh
# Library of the root guard of the Android emulator, sourced by arm.sh, guard.sh and disarm.sh from their install
# directory. Sourcing it sets variables and defines functions; it changes nothing on the host.
#
# Redroid runs Android in a privileged container on the host kernel: Android's init writes sysctls, changes owners and
# modes of /proc, /sys and tracefs entries, remounts debugfs and tracefs and creates tracefs instances, all of which the
# host shares. The guard records that state before a session (the reference), reverts every difference while Redroid
# runs and once it has stopped, proves the result on a second snapshot, and publishes a status file that
# `pnpm emulator:*` reads. Installed by root from the committed repository; `tools/emulator/src/guard/status.ts` reads
# what it writes.
#
# A snapshot holds one record per line, KIND<TAB>KEY<TAB>VALUE, sorted. tracked.tsv, generated by `pnpm gen` from
# tools/emulator/src/android-writes.ts, holds what Android is known to write and the settings of the guard.

PATH=/usr/sbin:/usr/bin:/sbin:/bin
LC_ALL=C
export PATH LC_ALL
umask 022

LIB=/usr/local/libexec/humanite-redroid
TRACKED=$LIB/tracked.tsv
RUN=/run/humanite-redroid
STATE=$RUN/state
SYSCTL_ROOT=/proc/sys
TRACEFS=/sys/kernel/tracing
DEBUGFS=/sys/kernel/debug
MOUNTINFO=/proc/self/mountinfo
BOOT_ID=/proc/sys/kernel/random/boot_id

STATUS_FORMAT=humanite-redroid-status/1
TAB=$(printf '\t')
# Plans separate their fields with the unit separator: `read` would merge two tabs around an empty value.
US=$(printf '\037')
ABSENT='<absent>'
NONE=-

PHASE=armed
MODE=arm
CONTAINER_STATUS=unknown
STARTED_AT=
RUN_FAILED=0

say() {
  printf 'humanite-redroid: %s\n' "$*" >&2
}

# setting NAME: the value of the `setting NAME VALUE` row of tracked.tsv.
setting() {
  awk -F "$TAB" -v name="$1" '$1 == "setting" && $2 == name { print $3; found = 1 } END { exit !found }' "$TRACKED"
}

# fail_run REASON DETAIL: records a failure of this run; failures stay in the status until the next arm. A failure
# the previous one repeats, as every run of a lasting problem does, is not recorded again.
fail_run() {
  RUN_FAILED=1
  say "$MODE: $1 $2"
  if [ -f "$STATE/failures.tsv" ] &&
    tail -n 1 "$STATE/failures.tsv" | awk -F "$TAB" -v mode="$MODE" -v reason="$1" -v detail="$2" \
      '$3 == mode && $4 == reason && $5 == detail { found = 1 } END { exit !found }'; then
    return
  fi
  printf 'failure\t%s\t%s\t%s\t%s\n' "$(date +%s)" "$MODE" "$1" "$2" >>"$STATE/failures.tsv"
}

# ---------------------------------------------------------------------------------------------------------------------
# Reading the host

# sysctl_records: the sysctls that can change (owner read and write) outside net/, which each network namespace has
# its own of. A value spanning lines cannot be written back: it is recorded with a leading `<multiline>`.
sysctl_records() {
  find "$SYSCTL_ROOT" -path "$SYSCTL_ROOT/net" -prune -o -type f -perm -0600 -print |
    awk -F "$TAB" -v tracked="$TRACKED" -v tab="$TAB" '
      BEGIN {
        while ((got = (getline row < tracked)) > 0) {
          split(row, field, "\t")
          if (field[1] == "skip" && field[2] == "sysctl") skip[field[3]] = 1
        }
        if (got < 0) exit 2
        close(tracked)
      }
      !($0 in skip) {
        value = ""
        lines = 0
        while ((got = (getline line < $0)) > 0) {
          gsub(/\t/, " ", line)
          value = lines == 0 ? line : value " " line
          lines++
        }
        close($0)
        if (got < 0) value = "<unreadable>"
        else if (lines > 1) value = "<multiline> " value
        print "sysctl" tab $0 tab value
      }'
}

# proc_records DIRECTORY: attributes of the entries of the procfs mounted at DIRECTORY, keyed as /proc paths, but the
# per-process directories, the views of this process's namespaces and symbolic links.
proc_records() {
  (cd "$1" && find . -xdev -mindepth 1 \
    \( -path './[0-9]*' -o -path ./self -o -path ./thread-self -o -path ./net -o -path ./sys \) -prune \
    -o ! -type l -printf 'procattr\t/proc/%P\t%m %U %G\n')
}

# fresh_proc_records: proc_records through a procfs mounted for this snapshot in a private mount namespace. The host's
# /proc keeps each inode with the attributes it had when first looked up, while chown and chmod from any mount,
# Redroid's included, change the kernel-wide entry that new inodes copy.
fresh_proc_records() {
  mkdir -p "$RUN/proc"
  # shellcheck disable=SC2016 # expanded by the inner shell
  unshare --mount --propagation private -- /bin/sh -c '
    . "$1" && mount -t proc -o ro,nosuid,nodev,noexec proc "$2" && proc_records "$2"
  ' sh "$LIB/lib.sh" "$RUN/proc"
}

# sysfs_records: attributes of the sysfs paths the `sysfsattr` rows of tracked.tsv list, and values of the files its
# `sysfsval` rows list, where they exist.
sysfs_records() {
  awk -F "$TAB" '$1 == "android" && ($2 == "sysfsattr" || $2 == "sysfsval") { print $2 "\t" $3 }' "$TRACKED" |
    while IFS="$TAB" read -r kind path; do
      if [ ! -e "$path" ] || [ -L "$path" ]; then
        continue
      fi
      if [ "$kind" = sysfsattr ]; then
        stat -c "sysfsattr$TAB%n$TAB%a %u %g" -- "$path"
      else
        printf 'sysfsval\t%s\t%s\n' "$path" "$(tr '\t\n' '  ' <"$path" | sed 's/ $//')"
      fi
    done
}

# mount_records: options of the debugfs and tracefs filesystems, which every mount of them shares, and the attributes
# of their mount points. The last line of a mount point is the mount visible there.
mount_records() {
  awk -v tab="$TAB" -v debugfs="$DEBUGFS" -v tracefs="$TRACEFS" '
    $5 == debugfs || $5 == tracefs {
      for (i = 7; $i != "-"; i++) continue
      options[$5] = $(i + 3)
    }
    END { for (point in options) print "superopts" tab point tab options[point] }' "$MOUNTINFO"
  stat -c "mountroot$TAB%n$TAB%a %u %g" -- "$DEBUGFS" "$TRACEFS"
}

# tracefs_records: attributes of every tracefs entry, its instances, and the values of the files tracked.tsv lists.
tracefs_records() {
  find "$TRACEFS" -xdev -mindepth 1 ! -type l -printf 'tracefsattr\t%p\t%m %U %G\n'
  find "$TRACEFS/instances" -mindepth 1 -maxdepth 1 -type d -printf 'tracefs-instance\t%f\tpresent\n'
  awk -F "$TAB" '$1 == "android" && $2 == "tracefsval" { print $3 }' "$TRACKED" | while IFS= read -r file; do
    printf 'tracefsval\t%s\t%s\n' "$file" "$(tr '\t\n' '  ' <"$TRACEFS/$file" | sed 's/ $//')"
  done
}

# missing_kinds SNAPSHOT: the kinds with fewer records than their `minimum` row requires: a reader that saw nothing
# would make every entry look removed.
missing_kinds() {
  awk -F "$TAB" '
    FILENAME == ARGV[1] { if ($1 == "minimum") minimum[$2] = $3; next }
    { count[$1]++ }
    END { for (kind in minimum) if (count[kind] + 0 < minimum[kind] + 0) print kind }' "$TRACKED" "$1" | sort
}

# snapshot FILE: every record of the host, sorted; FILE is written only when every reader succeeded.
snapshot() {
  if ! { sysctl_records && fresh_proc_records && sysfs_records && mount_records && tracefs_records; } >"$1.raw"; then
    return 1
  fi
  sort -t "$TAB" -k1,1 -k2,2 -u "$1.raw" >"$1.sorted"
  missing=$(missing_kinds "$1.sorted")
  if [ -n "$missing" ]; then
    say "snapshot without enough records of: $missing"
    return 1
  fi
  mv -f "$1.sorted" "$1"
  rm -f "$1.raw"
}

# ---------------------------------------------------------------------------------------------------------------------
# Deciding, without touching the host

# plan MODE REFERENCE NOW: one line per difference, ACTION KIND KEY WAS IS separated by US, sorted.
#   MODE idle: no container since the last restore; boot, tick: Redroid runs; stop: Redroid ran and no longer runs.
#   revert          a change Android is known to make: written back in every mode
#   revert-unknown  a change nothing attributes to Android while Redroid runs or has run: written back, the run fails
#   pending         a tracefs instance of Android: removed once Redroid stops
#   keep-unknown    a tracefs instance nothing attributes to Android, created during a session: kept, the run fails
#   unrevertable    a value the guard cannot write back: the run fails
#   accept          an entry that appeared or vanished, or a change in idle mode: out of a session, only a write of
#                   Android whose clean value tracked.tsv knows is reverted, since other tenants may write the others
plan() {
  awk -F "$TAB" -v OFS="$US" -v mode="$1" -v absent="$ABSENT" '
    function known(kind, key, value) {
      if (mode == "idle" && !((kind SUBSEP key) in clean)) return 0
      return ((kind SUBSEP key) in android && (android[kind SUBSEP key] == "*" || android[kind SUBSEP key] == value)) ||
        ((kind SUBSEP "*") in android && (android[kind SUBSEP "*"] == "*" || android[kind SUBSEP "*"] == value))
    }
    FILENAME == ARGV[1] {
      if ($1 == "android") android[$2 SUBSEP $3] = $4
      else if ($1 == "clean") clean[$2 SUBSEP $3] = $4
      else if ($1 == "volatile") volatile[$2 SUBSEP $3] = 1
      next
    }
    FILENAME == ARGV[2] { was[$1 SUBSEP $2] = $3; ids[$1 SUBSEP $2] = 1; next }
    { is[$1 SUBSEP $2] = $3; ids[$1 SUBSEP $2] = 1 }
    END {
      for (id in ids) {
        if (id in volatile) continue
        split(id, part, SUBSEP)
        kind = part[1]
        key = part[2]
        before = (id in was) ? was[id] : absent
        after = (id in is) ? is[id] : absent
        if (before == after) continue
        if (kind == "tracefs-instance" && before == absent) {
          if (known(kind, key, after)) action = mode == "boot" || mode == "tick" ? "pending" : "revert"
          else action = mode == "idle" ? "accept" : "keep-unknown"
        } else if (before == absent || after == absent) action = "accept"
        else if (substr(before, 1, 1) == "<" || substr(after, 1, 1) == "<") action = "unrevertable"
        else if (known(kind, key, after)) action = "revert"
        else action = mode == "idle" ? "accept" : "revert-unknown"
        print action, kind, key, before, after
      }
    }' "$TRACKED" "$2" "$3" | sort
}

# residue SNAPSHOT: what an earlier session left, which a reference must never record: the entries whose value differs
# from their `clean` row of tracked.tsv, as KIND KEY VALUE separated by tabs.
residue() {
  awk -F "$TAB" -v OFS="$TAB" -v absent="$ABSENT" '
    FILENAME == ARGV[1] { if ($1 == "clean") clean[$2 SUBSEP $3] = $4; next }
    { seen[$1 SUBSEP $2] = $3 }
    END {
      for (id in clean) {
        value = (id in seen) ? seen[id] : absent
        if (value != clean[id]) {
          split(id, part, SUBSEP)
          print part[1], part[2], value
        }
      }
    }' "$TRACKED" "$1" | sort
}

# remount_options SUPER-OPTIONS: the uid, gid and mode a remount gives back, from the options the reference recorded;
# debugfs and tracefs show them only when they differ from their defaults, root and 0700.
remount_options() {
  printf '%s\n' "$1" | awk -F , '
    BEGIN { option["uid"] = "0"; option["gid"] = "0"; option["mode"] = "700" }
    {
      for (i = 1; i <= NF; i++) {
        split($i, pair, "=")
        if (pair[1] in option) option[pair[1]] = pair[2]
      }
    }
    END { printf "uid=%s,gid=%s,mode=%s\n", option["uid"], option["gid"], option["mode"] }'
}

# ---------------------------------------------------------------------------------------------------------------------
# Writing the host

# set_attributes PATH "MODE UID GID": chown, then chmod. procfs copies an inode's owner, group and mode to the
# kernel-wide entry on every change, so both calls run even when the host's cached inode already shows the value.
set_attributes() {
  mode=${2%% *}
  ids=${2#* }
  uid=${ids%% *}
  gid=${ids#* }
  case "$mode:$uid:$gid" in
    *[!0-9:]* | :* | *::* | *:) return 1 ;;
  esac
  [ ! -L "$1" ] && chown -- "$uid:$gid" "$1" && chmod -- "$mode" "$1"
}

# revert_one KIND KEY VALUE: writes VALUE back; false when the key is not one the guard may write, or the write failed.
revert_one() {
  case $2 in
    *..* | *"$TAB"*) return 1 ;;
  esac
  case "$1:$2" in
    sysctl:"$SYSCTL_ROOT"/*) printf '%s\n' "$3" >"$2" ;;
    procattr:/proc/*) set_attributes "$2" "$3" ;;
    sysfsattr:/sys/kernel/debug* | sysfsattr:/sys/kernel/tracing* | sysfsval:/sys/kernel/debug* | sysfsval:/sys/kernel/tracing*) return 1 ;;
    sysfsattr:/sys/*) set_attributes "$2" "$3" ;;
    sysfsval:/sys/*) printf '%s\n' "$3" >"$2" ;;
    mountroot:"$DEBUGFS" | mountroot:"$TRACEFS") set_attributes "$2" "$3" ;;
    superopts:"$DEBUGFS" | superopts:"$TRACEFS") mount -o "remount,$(remount_options "$3")" -- "$2" ;;
    tracefsattr:"$TRACEFS"/*) set_attributes "$2" "$3" ;;
    tracefsval:*/*) return 1 ;;
    tracefsval:*) printf '%s\n' "$3" >"$TRACEFS/$2" ;;
    tracefs-instance:*/* | tracefs-instance:.*) return 1 ;;
    tracefs-instance:*) [ "$3" = "$ABSENT" ] && rmdir -- "$TRACEFS/instances/$2" ;;
    *) return 1 ;;
  esac
}

# apply PLAN: writes back every revert of PLAN; false when any write failed, each failure named on the error output.
apply() {
  failed=
  while IFS="$US" read -r action kind key before after; do
    case $action in
      revert | revert-unknown) ;;
      *) continue ;;
    esac
    if ! revert_one "$kind" "$key" "$before"; then
      say "cannot write back $kind $key: $before (now $after)"
      failed="$failed $kind:$key"
    fi
  done <"$1"
  WRITE_FAILURES=$failed
  [ -z "$failed" ]
}

# planned_keys "ACTION…" PLAN: the entries of PLAN with one of the actions, as ` KIND:KEY` each.
planned_keys() {
  awk -F "$US" -v actions="$1" 'index(" " actions " ", " " $1 " ") { printf " %s:%s", $2, $3 }' "$2"
}

# restore: snapshot, plan, write back, then prove it on a second snapshot; failures are recorded, never fatal here.
restore() {
  if ! snapshot "$STATE/now.tsv"; then
    fail_run capture-failed "first snapshot"
    return
  fi
  plan "$MODE" "$STATE/reference.tsv" "$STATE/now.tsv" >"$STATE/changes"
  if ! apply "$STATE/changes"; then
    fail_run write-failed "$WRITE_FAILURES"
  fi
  if ! snapshot "$STATE/after.tsv"; then
    fail_run capture-failed "second snapshot"
    return
  fi
  plan "$MODE" "$STATE/reference.tsv" "$STATE/after.tsv" |
    awk -F "$US" '$1 == "revert" || $1 == "revert-unknown"' >"$STATE/remaining"
  if [ -s "$STATE/remaining" ]; then
    fail_run not-restored "$(planned_keys 'revert revert-unknown' "$STATE/remaining")"
  fi
  unknown=$(planned_keys 'revert-unknown keep-unknown' "$STATE/changes")
  if [ -n "$unknown" ]; then
    fail_run unattributed "$unknown"
  fi
  unrevertable=$(planned_keys unrevertable "$STATE/changes")
  if [ -n "$unrevertable" ]; then
    fail_run unwritable-value "$unrevertable"
  fi
}

# write_status: publishes the state of this run, atomically, readable by every user.
write_status() {
  {
    printf 'format\t%s\n' "$STATUS_FORMAT"
    printf 'boot_id\t%s\n' "$(cat "$BOOT_ID")"
    printf 'armed_at\t%s\n' "$(cat "$STATE/armed_at")"
    printf 'phase\t%s\n' "$PHASE"
    printf 'mode\t%s\n' "$MODE"
    printf 'container\t%s\t%s\n' "$CONTAINER_STATUS" "${STARTED_AT:-$NONE}"
    if [ -s "$STATE/restored_started_at" ]; then
      printf 'restored_started_at\t%s\n' "$(cat "$STATE/restored_started_at")"
    else
      printf 'restored_started_at\t%s\n' "$NONE"
    fi
    printf 'run_end\t%s\n' "$(date +%s)"
    awk -v OFS="$TAB" '{ count = split($2, part, "/"); print "script", part[count], $1 }' "$STATE/scripts.sha256"
    if [ -f "$STATE/changes" ]; then
      awk -F "$US" -v OFS="$TAB" '{ $1 = $1; print "change", $0 }' "$STATE/changes"
    fi
    if [ -f "$STATE/remaining" ]; then
      awk -F "$US" -v OFS="$TAB" '{ $1 = $1; print "remaining", $0 }' "$STATE/remaining"
    fi
    if [ -f "$STATE/failures.tsv" ]; then
      cat "$STATE/failures.tsv"
    fi
  } >"$RUN/status.tmp"
  chmod 0644 "$RUN/status.tmp"
  mv -f "$RUN/status.tmp" "$RUN/status"
}

# ---------------------------------------------------------------------------------------------------------------------
# The container

# container_state NAME: sets CONTAINER_STATUS (a docker status, or absent) and STARTED_AT; false when docker cannot say.
container_state() {
  if inspected=$(timeout 10 docker container inspect --format '{{.State.Status}} {{.State.StartedAt}}' -- "$1" 2>"$STATE/docker.err"); then
    CONTAINER_STATUS=${inspected%% *}
    STARTED_AT=${inspected#* }
  elif grep -q 'No such container' "$STATE/docker.err"; then
    CONTAINER_STATUS=absent
    STARTED_AT=
  else
    say "docker container inspect $1: $(cat "$STATE/docker.err")"
    return 1
  fi
}

# booted NAME: whether Android in the container has completed its boot.
booted() {
  [ "$(timeout 10 docker exec -- "$1" /system/bin/getprop sys.boot_completed 2>/dev/null | tr -d '\r')" = 1 ]
}

# past_boot_deadline: whether the container started longer ago than the boot deadline; an unreadable start is.
past_boot_deadline() {
  started=$(date -d "$STARTED_AT" +%s 2>/dev/null) || return 0
  [ $(($(date +%s) - started)) -ge "$(setting boot_deadline_s)" ]
}

# ready_to_restore NAME: waits, within this run, until Android has booted or the boot deadline has passed: the host is
# then restored as soon as Android lets it. False when neither happens within `boot_wait_s`; the next run waits again.
ready_to_restore() {
  waited=0
  until booted "$1" || past_boot_deadline; do
    if [ "$waited" -ge "$(setting boot_wait_s)" ]; then
      return 1
    fi
    sleep 2
    waited=$((waited + 2))
  done
}

# ---------------------------------------------------------------------------------------------------------------------
# The three commands

# lock: holds the lock of the guard for the rest of the process: runs never overlap, and `pnpm emulator:up` takes the
# same lock around `docker run`.
lock() {
  exec 9>>"$RUN/lock"
  flock -w "$1" 9 || {
    say "another run holds $RUN/lock"
    exit 1
  }
}

record_scripts() {
  sha256sum "$LIB/arm.sh" "$LIB/guard.sh" "$LIB/disarm.sh" "$LIB/lib.sh" "$TRACKED" >"$STATE/scripts.sha256"
}

# arm_run: the reference of a clean host without Redroid, then the transient timer that runs guard.sh.
arm_run() {
  mkdir -p "$STATE"
  chmod 0755 "$RUN"
  chmod 0700 "$STATE"
  lock 120
  unit=$(setting unit)
  container=$(setting container)
  if systemctl is-active --quiet "$unit.timer"; then
    say "already armed: run disarm.sh first"
    exit 1
  fi
  container_state "$container" || exit 1
  if [ "$CONTAINER_STATUS" != absent ]; then
    say "container $container exists ($CONTAINER_STATUS): remove it with pnpm emulator:down before arming"
    exit 1
  fi
  find "$STATE" -mindepth 1 -maxdepth 1 -type f -delete
  date +%s >"$STATE/armed_at"
  record_scripts
  PHASE=armed
  MODE=arm
  if ! snapshot "$STATE/reference.tsv"; then
    fail_run capture-failed "reference"
  else
    residue "$STATE/reference.tsv" >"$STATE/residue"
    if [ -s "$STATE/residue" ]; then
      fail_run residue "$(awk -F "$TAB" '{ printf " %s:%s=%s", $1, $2, $3 }' "$STATE/residue")"
    fi
  fi
  write_status
  if [ "$RUN_FAILED" != 0 ]; then
    rm -f "$STATE/reference.tsv"
    exit 1
  fi
  # A transient unit whose last run failed stays loaded, and systemd-run refuses to create it again.
  systemctl reset-failed "$unit.timer" "$unit.service" 2>/dev/null || true
  systemd-run --unit="$unit" --description="Root guard of the Android emulator" \
    --on-active=5s --on-unit-active="$(setting tick_s)s" --timer-property=AccuracySec=1s \
    --property=Type=oneshot --property=TimeoutStartSec="$(setting run_timeout_s)" \
    "$LIB/guard.sh"
  systemctl is-active --quiet "$unit.timer" || {
    say "$unit.timer is not active"
    exit 1
  }
  printf 'armed: %s records in the reference, %s.timer active\n' "$(wc -l <"$STATE/reference.tsv")" "$unit"
}

# guard_run: one run of the timer.
guard_run() {
  lock 60
  if [ ! -s "$STATE/reference.tsv" ]; then
    say "not armed: run arm.sh"
    exit 1
  fi
  unit=$(setting unit)
  container=$(setting container)
  if ! sha256sum --check --status "$STATE/scripts.sha256"; then
    fail_run scripts-changed "installed files changed since arm.sh"
    write_status
    exit 1
  fi
  container_state "$container" || exit 1
  case $CONTAINER_STATUS in
    absent)
      if [ -f "$STATE/session" ]; then MODE=stop; else MODE=idle; fi
      ;;
    running)
      printf '%s\n' "$STARTED_AT" >"$STATE/session"
      if ! ready_to_restore "$container"; then
        PHASE=booting
        MODE='wait'
        rm -f "$STATE/changes" "$STATE/remaining"
        write_status
        exit 0
      fi
      if [ "$(cat "$STATE/restored_started_at" 2>/dev/null || true)" = "$STARTED_AT" ]; then MODE=tick; else MODE=boot; fi
      ;;
    *)
      printf '%s\n' "$STARTED_AT" >"$STATE/session"
      MODE=stop
      ;;
  esac
  restore
  case $MODE in
    boot | tick)
      PHASE=restored
      if [ "$RUN_FAILED" = 0 ]; then printf '%s\n' "$STARTED_AT" >"$STATE/restored_started_at"; fi
      rm -f "$STATE/absent_since"
      ;;
    stop | idle)
      PHASE=idle
      if [ "$RUN_FAILED" = 0 ]; then
        mv -f "$STATE/after.tsv" "$STATE/reference.tsv"
        if [ "$CONTAINER_STATUS" = absent ]; then rm -f "$STATE/session" "$STATE/restored_started_at"; fi
      fi
      ;;
  esac
  if [ "$MODE" = idle ] && [ "$RUN_FAILED" = 0 ]; then
    [ -s "$STATE/absent_since" ] || date +%s >"$STATE/absent_since"
    if [ $(($(date +%s) - $(cat "$STATE/absent_since"))) -ge "$(setting idle_ttl_s)" ]; then
      PHASE=closed
      MODE=close
      write_status
      systemctl stop --no-block "$unit.timer"
      exit 0
    fi
  fi
  write_status
  [ "$RUN_FAILED" = 0 ]
}

# disarm_run: a last restore without Redroid, then the timer stops.
disarm_run() {
  lock 180
  if [ ! -s "$STATE/reference.tsv" ]; then
    say "not armed"
    exit 1
  fi
  unit=$(setting unit)
  container=$(setting container)
  container_state "$container" || exit 1
  if [ "$CONTAINER_STATUS" != absent ]; then
    say "container $container exists ($CONTAINER_STATUS): run pnpm emulator:down first"
    exit 1
  fi
  if [ -f "$STATE/session" ]; then MODE=stop; else MODE=idle; fi
  PHASE=idle
  restore
  if [ "$RUN_FAILED" != 0 ]; then
    write_status
    say "host not restored: the timer keeps running, see $RUN/status"
    exit 1
  fi
  rm -f "$STATE/session" "$STATE/restored_started_at"
  systemctl stop "$unit.timer"
  if systemctl is-active --quiet "$unit.timer"; then
    say "$unit.timer is still active"
    exit 1
  fi
  PHASE=closed
  MODE=close
  write_status
  printf 'disarmed: host restored, %s.timer stopped\n' "$unit"
}
